package fr.orsay.lri.varna.genome;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Insets;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Hashtable;
import java.util.List;

import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.JToolBar;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.UIManager;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import javax.swing.border.TitledBorder;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.filechooser.FileFilter;

import fr.orsay.lri.varna.VARNAPanel;
import fr.orsay.lri.varna.applications.NussinovDemo;
import fr.orsay.lri.varna.applications.templateEditor.Couple;
import fr.orsay.lri.varna.exceptions.ExceptionNonEqualLength;
import fr.orsay.lri.varna.genome.GenomePanel.GenomePanelChange;
import fr.orsay.lri.varna.genome.GenomePanel.GenomePanelChangeListener;
import fr.orsay.lri.varna.interfaces.InterfaceVARNABasesListener;
import fr.orsay.lri.varna.interfaces.InterfaceVARNAListener;

public class GenomeGUI extends JFrame implements GenomePanelChangeListener, FocusListener {

	private static int DEFAULT_MAX_BP_SPAN = 410;

	GenomePanel _gpRef;
	String _seqRef = "AUUAAAGGUUUAUACCUUCCCAGGUAACAAACCAACCAACUUUCGAUCUCUUGUAGAUCUGUUCUCUAAACGAACUUUAAAAUCUGUGUGGCUGUCACUCGGCUGCAUGCUUAGUGCACUCACGCAGUAUAAUUAAUAACUAAUUACUGUCGUUGACAGGACACGAGUAACUCGUCUAUCUUCUGCAGGCUGCUUACGGUUUCGUCCGUGUUGCAGCCGAUCAUCAGCACAUCUAGGUUUUGUCCGGGUGUGACCGAAAGGUAAGAUGGAGAGCCUUGUCCCUGGUUUCAACGAGAAAACACACGUCCAACUCAGUUUGCCUGUUUUACAGGUUCGCGACGUGCUCGUACGUGGCUUUGGAGACUCCGUGGAGGAGGUCUUAUCAGAGGCACGUCAACAUCUUAAAGAUGGCACUUGUGGCUUAGUAGAAGUUGAAAAAGGCGUUUUGCCUCAACUUGAACAGCCCUAUGUGUUCAUCAAACGUUCGGAUGCUCGAACUGCACCUCAUGGUCAUGUUAUGGUUGAGCUGGUAGCAGAACUCGAAGGCAUUCAGUACGGUCGUAGUGGUGAGACACUUGGUGUCCUUGUCCCUCAUGUGGGCGAAAUACCAGUGGCUUACCGCAAGGUUCUUCUUCGUAAGAACGGUAAUAAAGGAGCUGGUGGCCAUAGUUACGGCGCCGAUCUAAAGUCAUUUGACUUAGGCGACGAGCUUGGCACUGAUCCUUAUGAAGAUUUUCAAGAAAACUGGAACACUAAACAUAGCAGUGGUGUUACCCGUGAACUCAUGCGUGAGCUUAACGGAGGGGCAUACACUCGCUAUGUCGAUAACAACUUCUGUGGCCCUGAUGGCUACCCUCUUGAGUGCAUUAAAGACCUUCUAGCACGUGCUGGUAAAGCUUCAUGCACUUUGUCCGAACAACUGGACUUUAUUGACACUAAGAGGGGUGUAUACUGCUGCCGUGAACAUGAGCAUGAAAUUGCUUGGUACACGGAACGUUCUGAAAAGAGCUAUGAAUUGCAGACACCUUUUGAAAUUAAAUUGGCAAAGAAAUUUGACACCUUCAAUGGGGAAUGUCCAAAUUUUGUAUUUCCCUUAAAUUCCAUAAUCAAGACUAUUCAACCAAGGGUUGAAAAGAAAAAGCUUGAUGGCUUUAUGGGUAGAAUUCGAUCUGUCUAUCCAGUUGCGUCACCAAAUGAAUGCAACCAAAUGUGCCUUUCAACUCUCAUGAAGUGUGAUCAUUGUGGUGAAACUUCAUGGCAGACGGGCGAUUUUGUUAAAGCCACUUGCGAAUUUUGUGGCACUGAGAAUUUGACUAAAGAAGGUGCCACUACUUGUGGUUACUUACCCCAAAAUGCUGUUGUUAAAAUUUAUUGUCCAGCAUGUCACAAUUCAGAAGUAGGACCUGAGCAUAGUCUUGCCGAAUACCAUAAUGAAUCUGGCUUGAAAACCAUUCUUCGUAAGGGUGGUCGCACUAUUGCCUUUGGAGGCUGUGUGUUCUCUUAUGUUGGUUGCCAUAACAAGUGUGCCUAUUGGGUUCCACGUGCUAGCGCUAACAUAGGUUGUAACCAUACAGGUGUUGUUGGAGAAGGUUCCGAAGGUCUUAAUGACAACCUUCUUGAAAUACUCCAAAAAGAGAAAGUCAACAUCAAUAUUGUUGGUGACUUUAAACUUAAUGAAGAGAUCGCCAUUAUUUUGGCAUCUUUUUCUGCUUCCACAAGUGCUUUUGUGGAAACUGUGAAAGGUUUGGAUUAUAAAGCAUUCAAACAAAUUGUUGAAUCCUGUGGUAAUUUUAAAGUUACAAAAGGAAAAGCUAAAAAAGGUGCCUGGAAUAUUGGUGAACAGAAAUCAAUACUGAGUCCUCUUUAUGCAUUUGCAUCAGAGGCUGCUCGUGUUGUACGAUCAAUUUUCUCCCGCACUCUUGAAACUGCUCAAAAUUCUGUGCGUGUUUUACAGAAGGCCGCUAUAACAAUACUAGAUGGAAUUUCACAGUAUUCACUGAGACUCAUUGAUGCUAUGAUGUUCACAUCUGAUUUGGCUACUAACAAUCUAGUUGUAAUGGCCUACAUUACAGGUGGUGUUGUUCAGUUGACUUCGCAGUGGCUAACUAACAUCUUUGGCACUGUUUAUGAAAAACUCAAACCCGUCCUUGAUUGGCUUGAAGAGAAGUUUAAGGAAGGUGUAGAGUUUCUUAGAGACGGUUGGGAAAUUGUUAAAUUUAUCUCAACCUGUGCUUGUGAAAUUGUCGGUGGACAAAUUGUCACCUGUGCAAAGGAAAUUAAGGAGAGUGUUCAGACAUUCUUUAAGCUUGUAAAUAAAUUUUUGGCUUUGUGUGCUGACUCUAUCAUUAUUGGUGGAGCUAAACUUAAAGCCUUGAAUUUAGGUGAAACAUUUGUCACGCACUCAAAGGGAUUGUACAGAAAGUGUGUUAAAUCCAGAGAAGAAACUGGCCUACUCAUGCCUCUAAAAGCCCCAAAAGAAAUUAUCUUCUUAGAGGGAGAAACACUUCCCACAGAAGUGUUAACAGAGGAAGUUGUCUUGAAAACUGGUGAUUUACAACCAUUAGAACAACCUACUAGUGAAGCUGUUGAAGCUCCAUUGGUUGGUACACCAGUUUGUAUUAACGGGCUUAUGUUGCUCGAAAUCAAAGACACAGAAAAGUACUGUGCCCUUGCACCUAAUAUGAUGGUAACAAACAAUACCUUCACACUCAAAGGCGGUGCACCAACAAAGGUUACUUUUGGUGAUGACACUGUGAUAGAAGUGCAAGGUUACAAGAGUGUGAAUAUCACUUUUGAACUUGAUGAAAGGAUUGAUAAAGUACUUAAUGAGAAGUGCUCUGCCUAUACAGUUGAACUCGGUACAGAAGUAAAUGAGUUCGCCUGUGUUGUGGCAGAUGCUGUCAUAAAAACUUUGCAACCAGUAUCUGAAUUACUUACACCACUGGGCAUUGAUUUAGAUGAGUGGAGUAUGGCUACAUACUACUUAUUUGAUGAGUCUGGUGAGUUUAAAUUGGCUUCACAUAUGUAUUGUUCUUUUUACCCUCCAGAUGAGGAUGAAGAAGAAGGUGAUUGUGAAGAAGAAGAGUUUGAGCCAUCAACUCAAUAUGAGUAUGGUACUGAAGAUGAUUACCAAGGUAAACCUUUGGAAUUUGGUGCCACUUCUGCUGCUCUUCAACCUGAAGAAGAGCAAGAAGAAGAUUGGUUAGAUGAUGAUAGUCAACAAACUGUUGGUCAACAAGACGGCAGUGAGGACAAUCAGACAACUACUAUUCAAACAAUUGUUGAGGUUCAACCUCAAUUAGAGAUGGAACUUACACCAGUUGUUCAGACUAUUGAAGUGAAUAGUUUUAGUGGUUAUUUAAAACUUACUGACAAUGUAUACAUUAAAAAUGCAGACAUUGUGGAAGAAGCUAAAAAGGUAAAACCAACAGUGGUUGUUAAUGCAGCCAAUGUUUACCUUAAACAUGGAGGAGGUGUUGCAGGAGCCUUAAAUAAGGCUACUAACAAUGCCAUGCAAGUUGAAUCUGAUGAUUACAUAGCUACUAAUGGACCACUUAAAGUGGGUGGUAGUUGUGUUUUAAGCGGACACAAUCUUGCUAAACACUGUCUUCAUGUUGUCGGCCCAAAUGUUAACAAAGGUGAAGACAUUCAACUUCUUAAGAGUGCUUAUGAAAAUUUUAAUCAGCACGAAGUUCUACUUGCACCAUUAUUAUCAGCUGGUAUUUUUGGUGCUGACCCUAUACAUUCUUUAAGAGUUUGUGUAGAUACUGUUCGCACAAAUGUCUACUUAGCUGUCUUUGAUAAAAAUCUCUAUGACAAACUUGUUUCAAGCUUUUUGGAAAUGAAGAGUGAAAAGCAAGUUGAACAAAAGAUCGCUGAGAUUCCUAAAGAGGAAGUUAAGCCAUUUAUAACUGAAAGUAAACCUUCAGUUGAACAGAGAAAACAAGAUGAUAAGAAAAUCAAAGCUUGUGUUGAAGAAGUUACAACAACUCUGGAAGAAACUAAGUUCCUCACAGAAAACUUGUUACUUUAUAUUGACAUUAAUGGCAAUCUUCAUCCAGAUUCUGCCACUCUUGUUAGUGACAUUGACAUCACUUUCUUAAAGAAAGAUGCUCCAUAUAUAGUGGGUGAUGUUGUUCAAGAGGGUGUUUUAACUGCUGUGGUUAUACCUACUAAAAAGGCUGGUGGCACUACUGAAAUGCUAGCGAAAGCUUUGAGAAAAGUGCCAACAGACAAUUAUAUAACCACUUACCCGGGUCAGGGUUUAAAUGGUUACACUGUAGAGGAGGCAAAGACAGUGCUUAAAAAGUGUAAAAGUGCCUUUUACAUUCUACCAUCUAUUAUCUCUAAUGAGAAGCAAGAAAUUCUUGGAACUGUUUCUUGGAAUUUGCGAGAAAUGCUUGCACAUGCAGAAGAAACACGCAAAUUAAUGCCUGUCUGUGUGGAAACUAAAGCCAUAGUUUCAACUAUACAGCGUAAAUAUAAGGGUAUUAAAAUACAAGAGGGUGUGGUUGAUUAUGGUGCUAGAUUUUACUUUUACACCAGUAAAACAACUGUAGCGUCACUUAUCAACACACUUAACGAUCUAAAUGAAACUCUUGUUACAAUGCCACUUGGCUAUGUAACACAUGGCUUAAAUUUGGAAGAAGCUGCUCGGUAUAUGAGAUCUCUCAAAGUGCCAGCUACAGUUUCUGUUUCUUCACCUGAUGCUGUUACAGCGUAUAAUGGUUAUCUUACUUCUUCUUCUAAAACACCUGAAGAACAUUUUAUUGAAACCAUCUCACUUGCUGGUUCCUAUAAAGAUUGGUCCUAUUCUGGACAAUCUACACAACUAGGUAUAGAAUUUCUUAAGAGAGGUGAUAAAAGUGUAUAUUACACUAGUAAUCCUACCACAUUCCACCUAGAUGGUGAAGUUAUCACCUUUGACAAUCUUAAGACACUUCUUUCUUUGAGAGAAGUGAGGACUAUUAAGGUGUUUACAACAGUAGACAACAUUAACCUCCACACGCAAGUUGUGGACAUGUCAAUGACAUAUGGACAACAGUUUGGUCCAACUUAUUUGGAUGGAGCUGAUGUUACUAAAAUAAAACCUCAUAAUUCACAUGAAGGUAAAACAUUUUAUGUUUUACCUAAUGAUGACACUCUACGUGUUGAGGCUUUUGAGUACUACCACACAACUGAUCCUAGUUUUCUGGGUAGGUACAUGUCAGCAUUAAAUCACACUAAAAAGUGGAAAUACCCACAAGUUAAUGGUUUAACUUCUAUUAAAUGGGCAGAUAACAACUGUUAUCUUGCCACUGCAUUGUUAACACUCCAACAAAUAGAGUUGAAGUUUAAUCCACCUGCUCUACAAGAUGCUUAUUACAGAGCAAGGGCUGGUGAAGCUGCUAACUUUUGUGCACUUAUCUUAGCCUACUGUAAUAAGACAGUAGGUGAGUUAGGUGAUGUUAGAGAAACAAUGAGUUACUUGUUUCAACAUGCCAAUUUAGAUUCUUGCAAAAGAGUCUUGAACGUGGUGUGUAAAACUUGUGGACAACAGCAGACAACCCUUAAGGGUGUAGAAGCUGUUAUGUACAUGGGCACACUUUCUUAUGAACAAUUUAAGAAAGGUGUUCAGAUACCUUGUACGUGUGGUAAACAAGCUACAAAAUAUCUAGUACAACAGGAGUCACCUUUUGUUAUGAUGUCAGCACCACCUGCUCAGUAUGAACUUAAGCAUGGUACAUUUACUUGUGCUAGUGAGUACACUGGUAAUUACCAGUGUGGUCACUAUAAACAUAUAACUUCUAAAGAAACUUUGUAUUGCAUAGACGGUGCUUUACUUACAAAGUCCUCAGAAUACAAAGGUCCUAUUACGGAUGUUUUCUACAAAGAAAACAGUUACACAACAACCAUAAAACCAGUUACUUAUAAAUUGGAUGGUGUUGUUUGUACAGAAAUUGACCCUAAGUUGGACAAUUAUUAUAAGAAAGACAAUUCUUAUUUCACAGAGCAACCAAUUGAUCUUGUACCAAACCAACCAUAUCCAAACGCAAGCUUCGAUAAUUUUAAGUUUGUAUGUGAUAAUAUCAAAUUUGCUGAUGAUUUAAACCAGUUAACUGGUUAUAAGAAACCUGCUUCAAGAGAGCUUAAAGUUACAUUUUUCCCUGACUUAAAUGGUGAUGUGGUGGCUAUUGAUUAUAAACACUACACACCCUCUUUUAAGAAAGGAGCUAAAUUGUUACAUAAACCUAUUGUUUGGCAUGUUAACAAUGCAACUAAUAAAGCCACGUAUAAACCAAAUACCUGGUGUAUACGUUGUCUUUGGAGCACAAAACCAGUUGAAACAUCAAAUUCGUUUGAUGUACUGAAGUCAGAGGACGCGCAGGGAAUGGAUAAUCUUGCCUGCGAAGAUCUAAAACCAGUCUCUGAAGAAGUAGUGGAAAAUCCUACCAUACAGAAAGACGUUCUUGAGUGUAAUGUGAAAACUACCGAAGUUGUAGGAGACAUUAUACUUAAACCAGCAAAUAAUAGUUUAAAAAUUACAGAAGAGGUUGGCCACACAGAUCUAAUGGCUGCUUAUGUAGACAAUUCUAGUCUUACUAUUAAGAAACCUAAUGAAUUAUCUAGAGUAUUAGGUUUGAAAACCCUUGCUACUCAUGGUUUAGCUGCUGUUAAUAGUGUCCCUUGGGAUACUAUAGCUAAUUAUGCUAAGCCUUUUCUUAACAAAGUUGUUAGUACAACUACUAACAUAGUUACACGGUGUUUAAACCGUGUUUGUACUAAUUAUAUGCCUUAUUUCUUUACUUUAUUGCUACAAUUGUGUACUUUUACUAGAAGUACAAAUUCUAGAAUUAAAGCAUCUAUGCCGACUACUAUAGCAAAGAAUACUGUUAAGAGUGUCGGUAAAUUUUGUCUAGAGGCUUCAUUUAAUUAUUUGAAGUCACCUAAUUUUUCUAAACUGAUAAAUAUUAUAAUUUGGUUUUUACUAUUAAGUGUUUGCCUAGGUUCUUUAAUCUACUCAACCGCUGCUUUAGGUGUUUUAAUGUCUAAUUUAGGCAUGCCUUCUUACUGUACUGGUUACAGAGAAGGCUAUUUGAACUCUACUAAUGUCACUAUUGCAACCUACUGUACUGGUUCUAUACCUUGUAGUGUUUGUCUUAGUGGUUUAGAUUCUUUAGACACCUAUCCUUCUUUAGAAACUAUACAAAUUACCAUUUCAUCUUUUAAAUGGGAUUUAACUGCUUUUGGCUUAGUUGCAGAGUGGUUUUUGGCAUAUAUUCUUUUCACUAGGUUUUUCUAUGUACUUGGAUUGGCUGCAAUCAUGCAAUUGUUUUUCAGCUAUUUUGCAGUACAUUUUAUUAGUAAUUCUUGGCUUAUGUGGUUAAUAAUUAAUCUUGUACAAAUGGCCCCGAUUUCAGCUAUGGUUAGAAUGUACAUCUUCUUUGCAUCAUUUUAUUAUGUAUGGAAAAGUUAUGUGCAUGUUGUAGACGGUUGUAAUUCAUCAACUUGUAUGAUGUGUUACAAACGUAAUAGAGCAACAAGAGUCGAAUGUACAACUAUUGUUAAUGGUGUUAGAAGGUCCUUUUAUGUCUAUGCUAAUGGAGGUAAAGGCUUUUGCAAACUACACAAUUGGAAUUGUGUUAAUUGUGAUACAUUCUGUGCUGGUAGUACAUUUAUUAGUGAUGAAGUUGCGAGAGACUUGUCACUACAGUUUAAAAGACCAAUAAAUCCUACUGACCAGUCUUCUUACAUCGUUGAUAGUGUUACAGUGAAGAAUGGUUCCAUCCAUCUUUACUUUGAUAAAGCUGGUCAAAAGACUUAUGAAAGACAUUCUCUCUCUCAUUUUGUUAACUUAGACAACCUGAGAGCUAAUAACACUAAAGGUUCAUUGCCUAUUAAUGUUAUAGUUUUUGAUGGUAAAUCAAAAUGUGAAGAAUCAUCUGCAAAAUCAGCGUCUGUUUACUACAGUCAGCUUAUGUGUCAACCUAUACUGUUACUAGAUCAGGCAUUAGUGUCUGAUGUUGGUGAUAGUGCGGAAGUUGCAGUUAAAAUGUUUGAUGCUUACGUUAAUACGUUUUCAUCAACUUUUAACGUACCAAUGGAAAAACUCAAAACACUAGUUGCAACUGCAGAAGCUGAACUUGCAAAGAAUGUGUCCUUAGACAAUGUCUUAUCUACUUUUAUUUCAGCAGCUCGGCAAGGGUUUGUUGAUUCAGAUGUAGAAACUAAAGAUGUUGUUGAAUGUCUUAAAUUGUCACAUCAAUCUGACAUAGAAGUUACUGGCGAUAGUUGUAAUAACUAUAUGCUCACCUAUAACAAAGUUGAAAACAUGACACCCCGUGACCUUGGUGCUUGUAUUGACUGUAGUGCGCGUCAUAUUAAUGCGCAGGUAGCAAAAAGUCACAACAUUGCUUUGAUAUGGAACGUUAAAGAUUUCAUGUCAUUGUCUGAACAACUACGAAAACAAAUACGUAGUGCUGCUAAAAAGAAUAACUUACCUUUUAAGUUGACAUGUGCAACUACUAGACAAGUUGUUAAUGUUGUAACAACAAAGAUAGCACUUAAGGGUGGUAAAAUUGUUAAUAAUUGGUUGAAGCAGUUAAUUAAAGUUACACUUGUGUUCCUUUUUGUUGCUGCUAUUUUCUAUUUAAUAACACCUGUUCAUGUCAUGUCUAAACAUACUGACUUUUCAAGUGAAAUCAUAGGAUACAAGGCUAUUGAUGGUGGUGUCACUCGUGACAUAGCAUCUACAGAUACUUGUUUUGCUAACAAACAUGCUGAUUUUGACACAUGGUUUAGCCAGCGUGGUGGUAGUUAUACUAAUGACAAAGCUUGCCCAUUGAUUGCUGCAGUCAUAACAAGAGAAGUGGGUUUUGUCGUGCCUGGUUUGCCUGGCACGAUAUUACGCACAACUAAUGGUGACUUUUUGCAUUUCUUACCUAGAGUUUUUAGUGCAGUUGGUAACAUCUGUUACACACCAUCAAAACUUAUAGAGUACACUGACUUUGCAACAUCAGCUUGUGUUUUGGCUGCUGAAUGUACAAUUUUUAAAGAUGCUUCUGGUAAGCCAGUACCAUAUUGUUAUGAUACCAAUGUACUAGAAGGUUCUGUUGCUUAUGAAAGUUUACGCCCUGACACACGUUAUGUGCUCAUGGAUGGCUCUAUUAUUCAAUUUCCUAACACCUACCUUGAAGGUUCUGUUAGAGUGGUAACAACUUUUGAUUCUGAGUACUGUAGGCACGGCACUUGUGAAAGAUCAGAAGCUGGUGUUUGUGUAUCUACUAGUGGUAGAUGGGUACUUAACAAUGAUUAUUACAGAUCUUUACCAGGAGUUUUCUGUGGUGUAGAUGCUGUAAAUUUACUUACUAAUAUGUUUACACCACUAAUUCAACCUAUUGGUGCUUUGGACAUAUCAGCAUCUAUAGUAGCUGGUGGUAUUGUAGCUAUCGUAGUAACAUGCCUUGCCUACUAUUUUAUGAGGUUUAGAAGAGCUUUUGGUGAAUACAGUCAUGUAGUUGCCUUUAAUACUUUACUAUUCCUUAUGUCAUUCACUGUACUCUGUUUAACACCAGUUUACUCAUUCUUACCUGGUGUUUAUUCUGUUAUUUACUUGUACUUGACAUUUUAUCUUACUAAUGAUGUUUCUUUUUUAGCACAUAUUCAGUGGAUGGUUAUGUUCACACCUUUAGUACCUUUCUGGAUAACAAUUGCUUAUAUCAUUUGUAUUUCCACAAAGCAUUUCUAUUGGUUCUUUAGUAAUUACCUAAAGAGACGUGUAGUCUUUAAUGGUGUUUCCUUUAGUACUUUUGAAGAAGCUGCGCUGUGCACCUUUUUGUUAAAUAAAGAAAUGUAUCUAAAGUUGCGUAGUGAUGUGCUAUUACCUCUUACGCAAUAUAAUAGAUACUUAGCUCUUUAUAAUAAGUACAAGUAUUUUAGUGGAGCAAUGGAUACAACUAGCUACAGAGAAGCUGCUUGUUGUCAUCUCGCAAAGGCUCUCAAUGACUUCAGUAACUCAGGUUCUGAUGUUCUUUACCAACCACCACAAACCUCUAUCACCUCAGCUGUUUUGCAGAGUGGUUUUAGAAAAAUGGCAUUCCCAUCUGGUAAAGUUGAGGGUUGUAUGGUACAAGUAACUUGUGGUACAACUACACUUAACGGUCUUUGGCUUGAUGACGUAGUUUACUGUCCAAGACAUGUGAUCUGCACCUCUGAAGACAUGCUUAACCCUAAUUAUGAAGAUUUACUCAUUCGUAAGUCUAAUCAUAAUUUCUUGGUACAGGCUGGUAAUGUUCAACUCAGGGUUAUUGGACAUUCUAUGCAAAAUUGUGUACUUAAGCUUAAGGUUGAUACAGCCAAUCCUAAGACACCUAAGUAUAAGUUUGUUCGCAUUCAACCAGGACAGACUUUUUCAGUGUUAGCUUGUUACAAUGGUUCACCAUCUGGUGUUUACCAAUGUGCUAUGAGGCCCAAUUUCACUAUUAAGGGUUCAUUCCUUAAUGGUUCAUGUGGUAGUGUUGGUUUUAACAUAGAUUAUGACUGUGUCUCUUUUUGUUACAUGCACCAUAUGGAAUUACCAACUGGAGUUCAUGCUGGCACAGACUUAGAAGGUAACUUUUAUGGACCUUUUGUUGACAGGCAAACAGCACAAGCAGCUGGUACGGACACAACUAUUACAGUUAAUGUUUUAGCUUGGUUGUACGCUGCUGUUAUAAAUGGAGACAGGUGGUUUCUCAAUCGAUUUACCACAACUCUUAAUGACUUUAACCUUGUGGCUAUGAAGUACAAUUAUGAACCUCUAACACAAGACCAUGUUGACAUACUAGGACCUCUUUCUGCUCAAACUGGAAUUGCCGUUUUAGAUAUGUGUGCUUCAUUAAAAGAAUUACUGCAAAAUGGUAUGAAUGGACGUACCAUAUUGGGUAGUGCUUUAUUAGAAGAUGAAUUUACACCUUUUGAUGUUGUUAGACAAUGCUCAGGUGUUACUUUCCAAAGUGCAGUGAAAAGAACAAUCAAGGGUACACACCACUGGUUGUUACUCACAAUUUUGACUUCACUUUUAGUUUUAGUCCAGAGUACUCAAUGGUCUUUGUUCUUUUUUUUGUAUGAAAAUGCCUUUUUACCUUUUGCUAUGGGUAUUAUUGCUAUGUCUGCUUUUGCAAUGAUGUUUGUCAAACAUAAGCAUGCAUUUCUCUGUUUGUUUUUGUUACCUUCUCUUGCCACUGUAGCUUAUUUUAAUAUGGUCUAUAUGCCUGCUAGUUGGGUGAUGCGUAUUAUGACAUGGUUGGAUAUGGUUGAUACUAGUUUGUCUGGUUUUAAGCUAAAAGACUGUGUUAUGUAUGCAUCAGCUGUAGUGUUACUAAUCCUUAUGACAGCAAGAACUGUGUAUGAUGAUGGUGCUAGGAGAGUGUGGACACUUAUGAAUGUCUUGACACUCGUUUAUAAAGUUUAUUAUGGUAAUGCUUUAGAUCAAGCCAUUUCCAUGUGGGCUCUUAUAAUCUCUGUUACUUCUAACUACUCAGGUGUAGUUACAACUGUCAUGUUUUUGGCCAGAGGUAUUGUUUUUAUGUGUGUUGAGUAUUGCCCUAUUUUCUUCAUAACUGGUAAUACACUUCAGUGUAUAAUGCUAGUUUAUUGUUUCUUAGGCUAUUUUUGUACUUGUUACUUUGGCCUCUUUUGUUUACUCAACCGCUACUUUAGACUGACUCUUGGUGUUUAUGAUUACUUAGUUUCUACACAGGAGUUUAGAUAUAUGAAUUCACAGGGACUACUCCCACCCAAGAAUAGCAUAGAUGCCUUCAAACUCAACAUUAAAUUGUUGGGUGUUGGUGGCAAACCUUGUAUCAAAGUAGCCACUGUACAGUCUAAAAUGUCAGAUGUAAAGUGCACAUCAGUAGUCUUACUCUCAGUUUUGCAACAACUCAGAGUAGAAUCAUCAUCUAAAUUGUGGGCUCAAUGUGUCCAGUUACACAAUGACAUUCUCUUAGCUAAAGAUACUACUGAAGCCUUUGAAAAAAUGGUUUCACUACUUUCUGUUUUGCUUUCCAUGCAGGGUGCUGUAGACAUAAACAAGCUUUGUGAAGAAAUGCUGGACAACAGGGCAACCUUACAAGCUAUAGCCUCAGAGUUUAGUUCCCUUCCAUCAUAUGCAGCUUUUGCUACUGCUCAAGAAGCUUAUGAGCAGGCUGUUGCUAAUGGUGAUUCUGAAGUUGUUCUUAAAAAGUUGAAGAAGUCUUUGAAUGUGGCUAAAUCUGAAUUUGACCGUGAUGCAGCCAUGCAACGUAAGUUGGAAAAGAUGGCUGAUCAAGCUAUGACCCAAAUGUAUAAACAGGCUAGAUCUGAGGACAAGAGGGCAAAAGUUACUAGUGCUAUGCAGACAAUGCUUUUCACUAUGCUUAGAAAGUUGGAUAAUGAUGCACUCAACAACAUUAUCAACAAUGCAAGAGAUGGUUGUGUUCCCUUGAACAUAAUACCUCUUACAACAGCAGCCAAACUAAUGGUUGUCAUACCAGACUAUAACACAUAUAAAAAUACGUGUGAUGGUACAACAUUUACUUAUGCAUCAGCAUUGUGGGAAAUCCAACAGGUUGUAGAUGCAGAUAGUAAAAUUGUUCAACUUAGUGAAAUUAGUAUGGACAAUUCACCUAAUUUAGCAUGGCCUCUUAUUGUAACAGCUUUAAGGGCCAAUUCUGCUGUCAAAUUACAGAAUAAUGAGCUUAGUCCUGUUGCACUACGACAGAUGUCUUGUGCUGCCGGUACUACACAAACUGCUUGCACUGAUGACAAUGCGUUAGCUUACUACAACACAACAAAGGGAGGUAGGUUUGUACUUGCACUGUUAUCCGAUUUACAGGAUUUGAAAUGGGCUAGAUUCCCUAAGAGUGAUGGAACUGGUACUAUCUAUACAGAACUGGAACCACCUUGUAGGUUUGUUACAGACACACCUAAAGGUCCUAAAGUGAAGUAUUUAUACUUUAUUAAAGGAUUAAACAACCUAAAUAGAGGUAUGGUACUUGGUAGUUUAGCUGCCACAGUACGUCUACAAGCUGGUAAUGCAACAGAAGUGCCUGCCAAUUCAACUGUAUUAUCUUUCUGUGCUUUUGCUGUAGAUGCUGCUAAAGCUUACAAAGAUUAUCUAGCUAGUGGGGGACAACCAAUCACUAAUUGUGUUAAGAUGUUGUGUACACACACUGGUACUGGUCAGGCAAUAACAGUUACACCGGAAGCCAAUAUGGAUCAAGAAUCCUUUGGUGGUGCAUCGUGUUGUCUGUACUGCCGUUGCCACAUAGAUCAUCCAAAUCCUAAAGGAUUUUGUGACUUAAAAGGUAAGUAUGUACAAAUACCUACAACUUGUGCUAAUGACCCUGUGGGUUUUACACUUAAAAACACAGUCUGUACCGUCUGCGGUAUGUGGAAAGGUUAUGGCUGUAGUUGUGAUCAACUCCGCGAACCCAUGCUUCAGUCAGCUGAUGCACAAUCGUUUUUAAACGGGUUUGCGGUGUAAGUGCAGCCCGUCUUACACCGUGCGGCACAGGCACUAGUACUGAUGUCGUAUACAGGGCUUUUGACAUCUACAAUGAUAAAGUAGCUGGUUUUGCUAAAUUCCUAAAAACUAAUUGUUGUCGCUUCCAAGAAAAGGACGAAGAUGACAAUUUAAUUGAUUCUUACUUUGUAGUUAAGAGACACACUUUCUCUAACUACCAACAUGAAGAAACAAUUUAUAAUUUACUUAAGGAUUGUCCAGCUGUUGCUAAACAUGACUUCUUUAAGUUUAGAAUAGACGGUGACAUGGUACCACAUAUAUCACGUCAACGUCUUACUAAAUACACAAUGGCAGACCUCGUCUAUGCUUUAAGGCAUUUUGAUGAAGGUAAUUGUGACACAUUAAAAGAAAUACUUGUCACAUACAAUUGUUGUGAUGAUGAUUAUUUCAAUAAAAAGGACUGGUAUGAUUUUGUAGAAAACCCAGAUAUAUUACGCGUAUACGCCAACUUAGGUGAACGUGUACGCCAAGCUUUGUUAAAAACAGUACAAUUCUGUGAUGCCAUGCGAAAUGCUGGUAUUGUUGGUGUACUGACAUUAGAUAAUCAAGAUCUCAAUGGUAACUGGUAUGAUUUCGGUGAUUUCAUACAAACCACGCCAGGUAGUGGAGUUCCUGUUGUAGAUUCUUAUUAUUCAUUGUUAAUGCCUAUAUUAACCUUGACCAGGGCUUUAACUGCAGAGUCACAUGUUGACACUGACUUAACAAAGCCUUACAUUAAGUGGGAUUUGUUAAAAUAUGACUUCACGGAAGAGAGGUUAAAACUCUUUGACCGUUAUUUUAAAUAUUGGGAUCAGACAUACCACCCAAAUUGUGUUAACUGUUUGGAUGACAGAUGCAUUCUGCAUUGUGCAAACUUUAAUGUUUUAUUCUCUACAGUGUUCCCACUUACAAGUUUUGGACCACUAGUGAGAAAAAUAUUUGUUGAUGGUGUUCCAUUUGUAGUUUCAACUGGAUACCACUUCAGAGAGCUAGGUGUUGUACAUAAUCAGGAUGUAAACUUACAUAGCUCUAGACUUAGUUUUAAGGAAUUACUUGUGUAUGCUGCUGACCCUGCUAUGCACGCUGCUUCUGGUAAUCUAUUACUAGAUAAACGCACUACGUGCUUUUCAGUAGCUGCACUUACUAACAAUGUUGCUUUUCAAACUGUCAAACCCGGUAAUUUUAACAAAGACUUCUAUGACUUUGCUGUGUCUAAGGGUUUCUUUAAGGAAGGAAGUUCUGUUGAAUUAAAACACUUCUUCUUUGCUCAGGAUGGUAAUGCUGCUAUCAGCGAUUAUGACUACUAUCGUUAUAAUCUACCAACAAUGUGUGAUAUCAGACAACUACUAUUUGUAGUUGAAGUUGUUGAUAAGUACUUUGAUUGUUACGAUGGUGGCUGUAUUAAUGCUAACCAAGUCAUCGUCAACAACCUAGACAAAUCAGCUGGUUUUCCAUUUAAUAAAUGGGGUAAGGCUAGACUUUAUUAUGAUUCAAUGAGUUAUGAGGAUCAAGAUGCACUUUUCGCAUAUACAAAACGUAAUGUCAUCCCUACUAUAACUCAAAUGAAUCUUAAGUAUGCCAUUAGUGCAAAGAAUAGAGCUCGCACCGUAGCUGGUGUCUCUAUCUGUAGUACUAUGACCAAUAGACAGUUUCAUCAAAAAUUAUUGAAAUCAAUAGCCGCCACUAGAGGAGCUACUGUAGUAAUUGGAACAAGCAAAUUCUAUGGUGGUUGGCACAACAUGUUAAAAACUGUUUAUAGUGAUGUAGAAAACCCUCACCUUAUGGGUUGGGAUUAUCCUAAAUGUGAUAGAGCCAUGCCUAACAUGCUUAGAAUUAUGGCCUCACUUGUUCUUGCUCGCAAACAUACAACGUGUUGUAGCUUGUCACACCGUUUCUAUAGAUUAGCUAAUGAGUGUGCUCAAGUAUUGAGUGAAAUGGUCAUGUGUGGCGGUUCACUAUAUGUUAAACCAGGUGGAACCUCAUCAGGAGAUGCCACAACUGCUUAUGCUAAUAGUGUUUUUAACAUUUGUCAAGCUGUCACGGCCAAUGUUAAUGCACUUUUAUCUACUGAUGGUAACAAAAUUGCCGAUAAGUAUGUCCGCAAUUUACAACACAGACUUUAUGAGUGUCUCUAUAGAAAUAGAGAUGUUGACACAGACUUUGUGAAUGAGUUUUACGCAUAUUUGCGUAAACAUUUCUCAAUGAUGAUACUCUCUGACGAUGCUGUUGUGUGUUUCAAUAGCACUUAUGCAUCUCAAGGUCUAGUGGCUAGCAUAAAGAACUUUAAGUCAGUUCUUUAUUAUCAAAACAAUGUUUUUAUGUCUGAAGCAAAAUGUUGGACUGAGACUGACCUUACUAAAGGACCUCAUGAAUUUUGCUCUCAACAUACAAUGCUAGUUAAACAGGGUGAUGAUUAUGUGUACCUUCCUUACCCAGAUCCAUCAAGAAUCCUAGGGGCCGGCUGUUUUGUAGAUGAUAUCGUAAAAACAGAUGGUACACUUAUGAUUGAACGGUUCGUGUCUUUAGCUAUAGAUGCUUACCCACUUACUAAACAUCCUAAUCAGGAGUAUGCUGAUGUCUUUCAUUUGUACUUACAAUACAUAAGAAAGCUACAUGAUGAGUUAACAGGACACAUGUUAGACAUGUAUUCUGUUAUGCUUACUAAUGAUAACACUUCAAGGUAUUGGGAACCUGAGUUUUAUGAGGCUAUGUACACACCGCAUACAGUCUUACAGGCUGUUGGGGCUUGUGUUCUUUGCAAUUCACAGACUUCAUUAAGAUGUGGUGCUUGCAUACGUAGACCAUUCUUAUGUUGUAAAUGCUGUUACGACCAUGUCAUAUCAACAUCACAUAAAUUAGUCUUGUCUGUUAAUCCGUAUGUUUGCAAUGCUCCAGGUUGUGAUGUCACAGAUGUGACUCAACUUUACUUAGGAGGUAUGAGCUAUUAUUGUAAAUCACAUAAACCACCCAUUAGUUUUCCAUUGUGUGCUAAUGGACAAGUUUUUGGUUUAUAUAAAAAUACAUGUGUUGGUAGCGAUAAUGUUACUGACUUUAAUGCAAUUGCAACAUGUGACUGGACAAAUGCUGGUGAUUACAUUUUAGCUAACACCUGUACUGAAAGACUCAAGCUUUUUGCAGCAGAAACGCUCAAAGCUACUGAGGAGACAUUUAAACUGUCUUAUGGUAUUGCUACUGUACGUGAAGUGCUGUCUGACAGAGAAUUACAUCUUUCAUGGGAAGUUGGUAAACCUAGACCACCACUUAACCGAAAUUAUGUCUUUACUGGUUAUCGUGUAACUAAAAACAGUAAAGUACAAAUAGGAGAGUACACCUUUGAAAAAGGUGACUAUGGUGAUGCUGUUGUUUACCGAGGUACAACAACUUACAAAUUAAAUGUUGGUGAUUAUUUUGUGCUGACAUCACAUACAGUAAUGCCAUUAAGUGCACCUACACUAGUGCCACAAGAGCACUAUGUUAGAAUUACUGGCUUAUACCCAACACUCAAUAUCUCAGAUGAGUUUUCUAGCAAUGUUGCAAAUUAUCAAAAGGUUGGUAUGCAAAAGUAUUCUACACUCCAGGGACCACCUGGUACUGGUAAGAGUCAUUUUGCUAUUGGCCUAGCUCUCUACUACCCUUCUGCUCGCAUAGUGUAUACAGCUUGCUCUCAUGCCGCUGUUGAUGCACUAUGUGAGAAGGCAUUAAAAUAUUUGCCUAUAGAUAAAUGUAGUAGAAUUAUACCUGCACGUGCUCGUGUAGAGUGUUUUGAUAAAUUCAAAGUGAAUUCAACAUUAGAACAGUAUGUCUUUUGUACUGUAAAUGCAUUGCCUGAGACGACAGCAGAUAUAGUUGUCUUUGAUGAAAUUUCAAUGGCCACAAAUUAUGAUUUGAGUGUUGUCAAUGCCAGAUUACGUGCUAAGCACUAUGUGUACAUUGGCGACCCUGCUCAAUUACCUGCACCACGCACAUUGCUAACUAAGGGCACACUAGAACCAGAAUAUUUCAAUUCAGUGUGUAGACUUAUGAAAACUAUAGGUCCAGACAUGUUCCUCGGAACUUGUCGGCGUUGUCCUGCUGAAAUUGUUGACACUGUGAGUGCUUUGGUUUAUGAUAAUAAGCUUAAAGCACAUAAAGACAAAUCAGCUCAAUGCUUUAAAAUGUUUUAUAAGGGUGUUAUCACGCAUGAUGUUUCAUCUGCAAUUAACAGGCCACAAAUAGGCGUGGUAAGAGAAUUCCUUACACGUAACCCUGCUUGGAGAAAAGCUGUCUUUAUUUCACCUUAUAAUUCACAGAAUGCUGUAGCCUCAAAGAUUUUGGGACUACCAACUCAAACUGUUGAUUCAUCACAGGGCUCAGAAUAUGACUAUGUCAUAUUCACUCAAACCACUGAAACAGCUCACUCUUGUAAUGUAAACAGAUUUAAUGUUGCUAUUACCAGAGCAAAAGUAGGCAUACUUUGCAUAAUGUCUGAUAGAGACCUUUAUGACAAGUUGCAAUUUACAAGUCUUGAAAUUCCACGUAGGAAUGUGGCAACUUUACAAGCUGAAAAUGUAACAGGACUCUUUAAAGAUUGUAGUAAGGUAAUCACUGGGUUACAUCCUACACAGGCACCUACACACCUCAGUGUUGACACUAAAUUCAAAACUGAAGGUUUAUGUGUUGACAUACCUGGCAUACCUAAGGACAUGACCUAUAGAAGACUCAUCUCUAUGAUGGGUUUUAAAAUGAAUUAUCAAGUUAAUGGUUACCCUAACAUGUUUAUCACCCGCGAAGAAGCUAUAAGACAUGUACGUGCAUGGAUUGGCUUCGAUGUCGAGGGGUGUCAUGCUACUAGAGAAGCUGUUGGUACCAAUUUACCUUUACAGCUAGGUUUUUCUACAGGUGUUAACCUAGUUGCUGUACCUACAGGUUAUGUUGAUACACCUAAUAAUACAGAUUUUUCCAGAGUUAGUGCUAAACCACCGCCUGGAGAUCAAUUUAAACACCUCAUACCACUUAUGUACAAAGGACUUCCUUGGAAUGUAGUGCGUAUAAAGAUUGUACAAAUGUUAAGUGACACACUUAAAAAUCUCUCUGACAGAGUCGUAUUUGUCUUAUGGGCACAUGGCUUUGAGUUGACAUCUAUGAAGUAUUUUGUGAAAAUAGGACCUGAGCGCACCUGUUGUCUAUGUGAUAGACGUGCCACAUGCUUUUCCACUGCUUCAGACACUUAUGCCUGUUGGCAUCAUUCUAUUGGAUUUGAUUACGUCUAUAAUCCGUUUAUGAUUGAUGUUCAACAAUGGGGUUUUACAGGUAACCUACAAAGCAACCAUGAUCUGUAUUGUCAAGUCCAUGGUAAUGCACAUGUAGCUAGUUGUGAUGCAAUCAUGACUAGGUGUCUAGCUGUCCACGAGUGCUUUGUUAAGCGUGUUGACUGGACUAUUGAAUAUCCUAUAAUUGGUGAUGAACUGAAGAUUAAUGCGGCUUGUAGAAAGGUUCAACACAUGGUUGUUAAAGCUGCAUUAUUAGCAGACAAAUUCCCAGUUCUUCACGACAUUGGUAACCCUAAAGCUAUUAAGUGUGUACCUCAAGCUGAUGUAGAAUGGAAGUUCUAUGAUGCACAGCCUUGUAGUGACAAAGCUUAUAAAAUAGAAGAAUUAUUCUAUUCUUAUGCCACACAUUCUGACAAAUUCACAGAUGGUGUAUGCCUAUUUUGGAAUUGCAAUGUCGAUAGAUAUCCUGCUAAUUCCAUUGUUUGUAGAUUUGACACUAGAGUGCUAUCUAACCUUAACUUGCCUGGUUGUGAUGGUGGCAGUUUGUAUGUAAAUAAACAUGCAUUCCACACACCAGCUUUUGAUAAAAGUGCUUUUGUUAAUUUAAAACAAUUACCAUUUUUCUAUUACUCUGACAGUCCAUGUGAGUCUCAUGGAAAACAAGUAGUGUCAGAUAUAGAUUAUGUACCACUAAAGUCUGCUACGUGUAUAACACGUUGCAAUUUAGGUGGUGCUGUCUGUAGACAUCAUGCUAAUGAGUACAGAUUGUAUCUCGAUGCUUAUAACAUGAUGAUCUCAGCUGGCUUUAGCUUGUGGGUUUACAAACAAUUUGAUACUUAUAACCUCUGGAACACUUUUACAAGACUUCAGAGUUUAGAAAAUGUGGCUUUUAAUGUUGUAAAUAAGGGACACUUUGAUGGACAACAGGGUGAAGUACCAGUUUCUAUCAUUAAUAACACUGUUUACACAAAAGUUGAUGGUGUUGAUGUAGAAUUGUUUGAAAAUAAAACAACAUUACCUGUUAAUGUAGCAUUUGAGCUUUGGGCUAAGCGCAACAUUAAACCAGUACCAGAGGUGAAAAUACUCAAUAAUUUGGGUGUGGACAUUGCUGCUAAUACUGUGAUCUGGGACUACAAAAGAGAUGCUCCAGCACAUAUAUCUACUAUUGGUGUUUGUUCUAUGACUGACAUAGCCAAGAAACCAACUGAAACGAUUUGUGCACCACUCACUGUCUUUUUUGAUGGUAGAGUUGAUGGUCAAGUAGACUUAUUUAGAAAUGCCCGUAAUGGUGUUCUUAUUACAGAAGGUAGUGUUAAAGGUUUACAACCAUCUGUAGGUCCCAAACAAGCUAGUCUUAAUGGAGUCACAUUAAUUGGAGAAGCCGUAAAAACACAGUUCAAUUAUUAUAAGAAAGUUGAUGGUGUUGUCCAACAAUUACCUGAAACUUACUUUACUCAGAGUAGAAAUUUACAAGAAUUUAAACCCAGGAGUCAAAUGGAAAUUGAUUUCUUAGAAUUAGCUAUGGAUGAAUUCAUUGAACGGUAUAAAUUAGAAGGCUAUGCCUUCGAACAUAUCGUUUAUGGAGAUUUUAGUCAUAGUCAGUUAGGUGGUUUACAUCUACUGAUUGGACUAGCUAAACGUUUUAAGGAAUCACCUUUUGAAUUAGAAGAUUUUAUUCCUAUGGACAGUACAGUUAAAAACUAUUUCAUAACAGAUGCGCAAACAGGUUCAUCUAAGUGUGUGUGUUCUGUUAUUGAUUUAUUACUUGAUGAUUUUGUUGAAAUAAUAAAAUCCCAAGAUUUAUCUGUAGUUUCUAAGGUUGUCAAAGUGACUAUUGACUAUACAGAAAUUUCAUUUAUGCUUUGGUGUAAAGAUGGCCAUGUAGAAACAUUUUACCCAAAAUUACAAUCUAGUCAAGCGUGGCAACCGGGUGUUGCUAUGCCUAAUCUUUACAAAAUGCAAAGAAUGCUAUUAGAAAAGUGUGACCUUCAAAAUUAUGGUGAUAGUGCAACAUUACCUAAAGGCAUAAUGAUGAAUGUCGCAAAAUAUACUCAACUGUGUCAAUAUUUAAACACAUUAACAUUAGCUGUACCCUAUAAUAUGAGAGUUAUACAUUUUGGUGCUGGUUCUGAUAAAGGAGUUGCACCAGGUACAGCUGUUUUAAGACAGUGGUUGCCUACGGGUACGCUGCUUGUCGAUUCAGAUCUUAAUGACUUUGUCUCUGAUGCAGAUUCAACUUUGAUUGGUGAUUGUGCAACUGUACAUACAGCUAAUAAAUGGGAUCUCAUUAUUAGUGAUAUGUACGACCCUAAGACUAAAAAUGUUACAAAAGAAAAUGACUCUAAAGAGGGUUUUUUCACUUACAUUUGUGGGUUUAUACAACAAAAGCUAGCUCUUGGAGGUUCCGUGGCUAUAAAGAUAACAGAACAUUCUUGGAAUGCUGAUCUUUAUAAGCUCAUGGGACACUUCGCAUGGUGGACAGCCUUUGUUACUAAUGUGAAUGCGUCAUCAUCUGAAGCAUUUUUAAUUGGAUGUAAUUAUCUUGGCAAACCACGCGAACAAAUAGAUGGUUAUGUCAUGCAUGCAAAUUACAUAUUUUGGAGGAAUACAAAUCCAAUUCAGUUGUCUUCCUAUUCUUUAUUUGACAUGAGUAAAUUUCCCCUUAAAUUAAGGGGUACUGCUGUUAUGUCUUUAAAAGAAGGUCAAAUCAAUGAUAUGAUUUUAUCUCUUCUUAGUAAAGGUAGACUUAUAAUUAGAGAAAACAACAGAGUUGUUAUUUCUAGUGAUGUUCUUGUUAACAACUAAACGAACAAUGUUUGUUUUUCUUGUUUUAUUGCCACUAGUCUCUAGUCAGUGUGUUAAUCUUACAACCAGAACUCAAUUACCCCCUGCAUACACUAAUUCUUUCACACGUGGUGUUUAUUACCCUGACAAAGUUUUCAGAUCCUCAGUUUUACAUUCAACUCAGGACUUGUUCUUACCUUUCUUUUCCAAUGUUACUUGGUUCCAUGCUAUACAUGUCUCUGGGACCAAUGGUACUAAGAGGUUUGAUAACCCUGUCCUACCAUUUAAUGAUGGUGUUUAUUUUGCUUCCACUGAGAAGUCUAACAUAAUAAGAGGCUGGAUUUUUGGUACUACUUUAGAUUCGAAGACCCAGUCCCUACUUAUUGUUAAUAACGCUACUAAUGUUGUUAUUAAAGUCUGUGAAUUUCAAUUUUGUAAUGAUCCAUUUUUGGGUGUUUAUUACCACAAAAACAACAAAAGUUGGAUGGAAAGUGAGUUCAGAGUUUAUUCUAGUGCGAAUAAUUGCACUUUUGAAUAUGUCUCUCAGCCUUUUCUUAUGGACCUUGAAGGAAAACAGGGUAAUUUCAAAAAUCUUAGGGAAUUUGUGUUUAAGAAUAUUGAUGGUUAUUUUAAAAUAUAUUCUAAGCACACGCCUAUUAAUUUAGUGCGUGAUCUCCCUCAGGGUUUUUCGGCUUUAGAACCAUUGGUAGAUUUGCCAAUAGGUAUUAACAUCACUAGGUUUCAAACUUUACUUGCUUUACAUAGAAGUUAUUUGACUCCUGGUGAUUCUUCUUCAGGUUGGACAGCUGGUGCUGCAGCUUAUUAUGUGGGUUAUCUUCAACCUAGGACUUUUCUAUUAAAAUAUAAUGAAAAUGGAACCAUUACAGAUGCUGUAGACUGUGCACUUGACCCUCUCUCAGAAACAAAGUGUACGUUGAAAUCCUUCACUGUAGAAAAAGGAAUCUAUCAAACUUCUAACUUUAGAGUCCAACCAACAGAAUCUAUUGUUAGAUUUCCUAAUAUUACAAACUUGUGCCCUUUUGGUGAAGUUUUUAACGCCACCAGAUUUGCAUCUGUUUAUGCUUGGAACAGGAAGAGAAUCAGCAACUGUGUUGCUGAUUAUUCUGUCCUAUAUAAUUCCGCAUCAUUUUCCACUUUUAAGUGUUAUGGAGUGUCUCCUACUAAAUUAAAUGAUCUCUGCUUUACUAAUGUCUAUGCAGAUUCAUUUGUAAUUAGAGGUGAUGAAGUCAGACAAAUCGCUCCAGGGCAAACUGGAAAGAUUGCUGAUUAUAAUUAUAAAUUACCAGAUGAUUUUACAGGCUGCGUUAUAGCUUGGAAUUCUAACAAUCUUGAUUCUAAGGUUGGUGGUAAUUAUAAUUACCUGUAUAGAUUGUUUAGGAAGUCUAAUCUCAAACCUUUUGAGAGAGAUAUUUCAACUGAAAUCUAUCAGGCCGGUAGCACACCUUGUAAUGGUGUUGAAGGUUUUAAUUGUUACUUUCCUUUACAAUCAUAUGGUUUCCAACCCACUAAUGGUGUUGGUUACCAACCAUACAGAGUAGUAGUACUUUCUUUUGAACUUCUACAUGCACCAGCAACUGUUUGUGGACCUAAAAAGUCUACUAAUUUGGUUAAAAACAAAUGUGUCAAUUUCAACUUCAAUGGUUUAACAGGCACAGGUGUUCUUACUGAGUCUAACAAAAAGUUUCUGCCUUUCCAACAAUUUGGCAGAGACAUUGCUGACACUACUGAUGCUGUCCGUGAUCCACAGACACUUGAGAUUCUUGACAUUACACCAUGUUCUUUUGGUGGUGUCAGUGUUAUAACACCAGGAACAAAUACUUCUAACCAGGUUGCUGUUCUUUAUCAGGGUGUUAACUGCACAGAAGUCCCUGUUGCUAUUCAUGCAGAUCAACUUACUCCUACUUGGCGUGUUUAUUCUACAGGUUCUAAUGUUUUUCAAACACGUGCAGGCUGUUUAAUAGGGGCUGAACAUGUCAACAACUCAUAUGAGUGUGACAUACCCAUUGGUGCAGGUAUAUGCGCUAGUUAUCAGACUCAGACUAAUUCUCCUCGGCGGGCACGUAGUGUAGCUAGUCAAUCCAUCAUUGCCUACACUAUGUCACUUGGUGCAGAAAAUUCAGUUGCUUACUCUAAUAACUCUAUUGCCAUACCCACAAAUUUUACUAUUAGUGUUACCACAGAAAUUCUACCAGUGUCUAUGACCAAGACAUCAGUAGAUUGUACAAUGUACAUUUGUGGUGAUUCAACUGAAUGCAGCAAUCUUUUGUUGCAAUAUGGCAGUUUUUGUACACAAUUAAACCGUGCUUUAACUGGAAUAGCUGUUGAACAAGACAAAAACACCCAAGAAGUUUUUGCACAAGUCAAACAAAUUUACAAAACACCACCAAUUAAAGAUUUUGGUGGUUUUAAUUUUUCACAAAUAUUACCAGAUCCAUCAAAACCAAGCAAGAGGUCAUUUAUUGAAGAUCUACUUUUCAACAAAGUGACACUUGCAGAUGCUGGCUUCAUCAAACAAUAUGGUGAUUGCCUUGGUGAUAUUGCUGCUAGAGACCUCAUUUGUGCACAAAAGUUUAACGGCCUUACUGUUUUGCCACCUUUGCUCACAGAUGAAAUGAUUGCUCAAUACACUUCUGCACUGUUAGCGGGUACAAUCACUUCUGGUUGGACCUUUGGUGCAGGUGCUGCAUUACAAAUACCAUUUGCUAUGCAAAUGGCUUAUAGGUUUAAUGGUAUUGGAGUUACACAGAAUGUUCUCUAUGAGAACCAAAAAUUGAUUGCCAACCAAUUUAAUAGUGCUAUUGGCAAAAUUCAAGACUCACUUUCUUCCACAGCAAGUGCACUUGGAAAACUUCAAGAUGUGGUCAACCAAAAUGCACAAGCUUUAAACACGCUUGUUAAACAACUUAGCUCCAAUUUUGGUGCAAUUUCAAGUGUUUUAAAUGAUAUCCUUUCACGUCUUGACAAAGUUGAGGCUGAAGUGCAAAUUGAUAGGUUGAUCACAGGCAGACUUCAAAGUUUGCAGACAUAUGUGACUCAACAAUUAAUUAGAGCUGCAGAAAUCAGAGCUUCUGCUAAUCUUGCUGCUACUAAAAUGUCAGAGUGUGUACUUGGACAAUCAAAAAGAGUUGAUUUUUGUGGAAAGGGCUAUCAUCUUAUGUCCUUCCCUCAGUCAGCACCUCAUGGUGUAGUCUUCUUGCAUGUGACUUAUGUCCCUGCACAAGAAAAGAACUUCACAACUGCUCCUGCCAUUUGUCAUGAUGGAAAAGCACACUUUCCUCGUGAAGGUGUCUUUGUUUCAAAUGGCACACACUGGUUUGUAACACAAAGGAAUUUUUAUGAACCACAAAUCAUUACUACAGACAACACAUUUGUGUCUGGUAACUGUGAUGUUGUAAUAGGAAUUGUCAACAACACAGUUUAUGAUCCUUUGCAACCUGAAUUAGACUCAUUCAAGGAGGAGUUAGAUAAAUAUUUUAAGAAUCAUACAUCACCAGAUGUUGAUUUAGGUGACAUCUCUGGCAUUAAUGCUUCAGUUGUAAACAUUCAAAAAGAAAUUGACCGCCUCAAUGAGGUUGCCAAGAAUUUAAAUGAAUCUCUCAUCGAUCUCCAAGAACUUGGAAAGUAUGAGCAGUAUAUAAAAUGGCCAUGGUACAUUUGGCUAGGUUUUAUAGCUGGCUUGAUUGCCAUAGUAAUGGUGACAAUUAUGCUUUGCUGUAUGACCAGUUGCUGUAGUUGUCUCAAGGGCUGUUGUUCUUGUGGAUCCUGCUGCAAAUUUGAUGAAGACGACUCUGAGCCAGUGCUCAAAGGAGUCAAAUUACAUUACACAUAAACGAACUUAUGGAUUUGUUUAUGAGAAUCUUCACAAUUGGAACUGUAACUUUGAAGCAAGGUGAAAUCAAGGAUGCUACUCCUUCAGAUUUUGUUCGCGCUACUGCAACGAUACCGAUACAAGCCUCACUCCCUUUCGGAUGGCUUAUUGUUGGCGUUGCACUUCUUGCUGUUUUUCAGAGCGCUUCCAAAAUCAUAACCCUCAAAAAGAGAUGGCAACUAGCACUCUCCAAGGGUGUUCACUUUGUUUGCAACUUGCUGUUGUUGUUUGUAACAGUUUACUCACACCUUUUGCUCGUUGCUGCUGGCCUUGAAGCCCCUUUUCUCUAUCUUUAUGCUUUAGUCUACUUCUUGCAGAGUAUAAACUUUGUAAGAAUAAUAAUGAGGCUUUGGCUUUGCUGGAAAUGCCGUUCCAAAAACCCAUUACUUUAUGAUGCCAACUAUUUUCUUUGCUGGCAUACUAAUUGUUACGACUAUUGUAUACCUUACAAUAGUGUAACUUCUUCAAUUGUCAUUACUUCAGGUGAUGGCACAACAAGUCCUAUUUCUGAACAUGACUACCAGAUUGGUGGUUAUACUGAAAAAUGGGAAUCUGGAGUAAAAGACUGUGUUGUAUUACACAGUUACUUCACUUCAGACUAUUACCAGCUGUACUCAACUCAAUUGAGUACAGACACUGGUGUUGAACAUGUUACCUUCUUCAUCUACAAUAAAAUUGUUGAUGAGCCUGAAGAACAUGUCCAAAUUCACACAAUCGACGGUUCAUCCGGAGUUGUUAAUCCAGUAAUGGAACCAAUUUAUGAUGAACCGACGACGACUACUAGCGUGCCUUUGUAAGCACAAGCUGAUGAGUACGAACUUAUGUACUCAUUCGUUUCGGAAGAGACAGGUACGUUAAUAGUUAAUAGCGUACUUCUUUUUCUUGCUUUCGUGGUAUUCUUGCUAGUUACACUAGCCAUCCUUACUGCGCUUCGAUUGUGUGCGUACUGCUGCAAUAUUGUUAACGUGAGUCUUGUAAAACCUUCUUUUUACGUUUACUCUCGUGUUAAAAAUCUGAAUUCUUCUAGAGUUCCUGAUCUUCUGGUCUAAACGAACUAAAUAUUAUAUUAGUUUUUCUGUUUGGAACUUUAAUUUUAGCCAUGGCAGAUUCCAACGGUACUAUUACCGUUGAAGAGCUUAAAAAGCUCCUUGAACAAUGGAACCUAGUAAUAGGUUUCCUAUUCCUUACAUGGAUUUGUCUUCUACAAUUUGCCUAUGCCAACAGGAAUAGGUUUUUGUAUAUAAUUAAGUUAAUUUUCCUCUGGCUGUUAUGGCCAGUAACUUUAGCUUGUUUUGUGCUUGCUGCUGUUUACAGAAUAAAUUGGAUCACCGGUGGAAUUGCUAUCGCAAUGGCUUGUCUUGUAGGCUUGAUGUGGCUCAGCUACUUCAUUGCUUCUUUCAGACUGUUUGCGCGUACGCGUUCCAUGUGGUCAUUCAAUCCAGAAACUAACAUUCUUCUCAACGUGCCACUCCAUGGCACUAUUCUGACCAGACCGCUUCUAGAAAGUGAACUCGUAAUCGGAGCUGUGAUCCUUCGUGGACAUCUUCGUAUUGCUGGACACCAUCUAGGACGCUGUGACAUCAAGGACCUGCCUAAAGAAAUCACUGUUGCUACAUCACGAACGCUUUCUUAUUACAAAUUGGGAGCUUCGCAGCGUGUAGCAGGUGACUCAGGUUUUGCUGCAUACAGUCGCUACAGGAUUGGCAACUAUAAAUUAAACACAGACCAUUCCAGUAGCAGUGACAAUAUUGCUUUGCUUGUACAGUAAGUGACAACAGAUGUUUCAUCUCGUUGACUUUCAGGUUACUAUAGCAGAGAUAUUACUAAUUAUUAUGAGGACUUUUAAAGUUUCCAUUUGGAAUCUUGAUUACAUCAUAAACCUCAUAAUUAAAAAUUUAUCUAAGUCACUAACUGAGAAUAAAUAUUCUCAAUUAGAUGAAGAGCAACCAAUGGAGAUUGAUUAAACGAACAUGAAAAUUAUUCUUUUCUUGGCACUGAUAACACUCGCUACUUGUGAGCUUUAUCACUACCAAGAGUGUGUUAGAGGUACAACAGUACUUUUAAAAGAACCUUGCUCUUCUGGAACAUACGAGGGCAAUUCACCAUUUCAUCCUCUAGCUGAUAACAAAUUUGCACUGACUUGCUUUAGCACUCAAUUUGCUUUUGCUUGUCCUGACGGCGUAAAACACGUCUAUCAGUUACGUGCCAGAUCAGUUUCACCUAAACUGUUCAUCAGACAAGAGGAAGUUCAAGAACUUUACUCUCCAAUUUUUCUUAUUGUUGCGGCAAUAGUGUUUAUAACACUUUGCUUCACACUCAAAAGAAAGACAGAAUGAUUGAACUUUCAUUAAUUGACUUCUAUUUGUGCUUUUUAGCCUUUCUGCUAUUCCUUGUUUUAAUUAUGCUUAUUAUCUUUUGGUUCUCACUUGAACUGCAAGAUCAUAAUGAAACUUGUCACGCCUAAACGAACAUGAAAUUUCUUGUUUUCUUAGGAAUCAUCACAACUGUAGCUGCAUUUCACCAAGAAUGUAGUUUACAGUCAUGUACUCAACAUCAACCAUAUGUAGUUGAUGACCCGUGUCCUAUUCACUUCUAUUCUAAAUGGUAUAUUAGAGUAGGAGCUAGAAAAUCAGCACCUUUAAUUGAAUUGUGCGUGGAUGAGGCUGGUUCUAAAUCACCCAUUCAGUACAUCGAUAUCGGUAAUUAUACAGUUUCCUGUUUACCUUUUACAAUUAAUUGCCAGGAACCUAAAUUGGGUAGUCUUGUAGUGCGUUGUUCGUUCUAUGAAGACUUUUUAGAGUAUCAUGACGUUCGUGUUGUUUUAGAUUUCAUCUAAACGAACAAACUAAAAUGUCUGAUAAUGGACCCCAAAAUCAGCGAAAUGCACCCCGCAUUACGUUUGGUGGACCCUCAGAUUCAACUGGCAGUAACCAGAAUGGAGAACGCAGUGGGGCGCGAUCAAAACAACGUCGGCCCCAAGGUUUACCCAAUAAUACUGCGUCUUGGUUCACCGCUCUCACUCAACAUGGCAAGGAAGACCUUAAAUUCCCUCGAGGACAAGGCGUUCCAAUUAACACCAAUAGCAGUCCAGAUGACCAAAUUGGCUACUACCGAAGAGCUACCAGACGAAUUCGUGGUGGUGACGGUAAAAUGAAAGAUCUCAGUCCAAGAUGGUAUUUCUACUACCUAGGAACUGGGCCAGAAGCUGGACUUCCCUAUGGUGCUAACAAAGACGGCAUCAUAUGGGUUGCAACUGAGGGAGCCUUGAAUACACCAAAAGAUCACAUUGGCACCCGCAAUCCUGCUAACAAUGCUGCAAUCGUGCUACAACUUCCUCAAGGAACAACAUUGCCAAAAGGCUUCUACGCAGAAGGGAGCAGAGGCGGCAGUCAAGCCUCUUCUCGUUCCUCAUCACGUAGUCGCAACAGUUCAAGAAAUUCAACUCCAGGCAGCAGUAGGGGAACUUCUCCUGCUAGAAUGGCUGGCAAUGGCGGUGAUGCUGCUCUUGCUUUGCUGCUGCUUGACAGAUUGAACCAGCUUGAGAGCAAAAUGUCUGGUAAAGGCCAACAACAACAAGGCCAAACUGUCACUAAGAAAUCUGCUGCUGAGGCUUCUAAGAAGCCUCGGCAAAAACGUACUGCCACUAAAGCAUACAAUGUAACACAAGCUUUCGGCAGACGUGGUCCAGAACAAACCCAAGGAAAUUUUGGGGACCAGGAACUAAUCAGACAAGGAACUGAUUACAAACAUUGGCCGCAAAUUGCACAAUUUGCCCCCAGCGCUUCAGCGUUCUUCGGAAUGUCGCGCAUUGGCAUGGAAGUCACACCUUCGGGAACGUGGUUGACCUACACAGGUGCCAUCAAAUUGGAUGACAAAGAUCCAAAUUUCAAAGAUCAAGUCAUUUUGCUGAAUAAGCAUAUUGACGCAUACAAAACAUUCCCACCAACAGAGCCUAAAAAGGACAAAAAGAAGAAGGCUGAUGAAACUCAAGCCUUACCGCAGAGACAGAAGAAACAGCAAACUGUGACUCUUCUUCCUGCUGCAGAUUUGGAUGAUUUCUCCAAACAAUUGCAACAAUCCAUGAGCAGUGCUGACUCAACUCAGGCCUAAACUCAUGCAGACCACACAAGGCAGAUGGGCUAUAUAAACGUUUUCGCUUUUCCGUUUACGAUAUAUAGUCUACUCUUGUGCAGAAUGAAUUCUCGUAACUACAUAGCACAAGUAGAUGUAGUUAACUUUAAUCUCACAUAGCAAUCUUUAAUCAGUGUGUAACAUUAGGGAGGACUUGAAAGAGCCACCACAUUUUCACCGAGGCCACGCGGAGUACGAUCGAGUGUACAGUGAACAAUGCUAGGGAGAGCUGCCUAUAUGGAAGAGCCCUAAUGUGUAAAAUUAAUUUUAGUAGUGCUAUCCCCAUGUGAUUUUAAUAGCUUCUUAGGAGAAUGACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	String _strRef = "......(((((.(((((....)))))..)))))..((.......(((((.....))))).((((.......))))........((((((((.((.((((.(((.....))).)))))).))))))))......................(((((((((((..(((((...(((.(((((((((((..((((((.(((((......)))))..))))))......)))(((((((.((......)))))))))(((....)))))))))))))).))))).))))...))))))).......((((((.......((..((((((...))))))..)))))))).....(((((.(((((((((((((.....)))).)))..)))))).)))))............((((((((.((.((((..((..(((((((....(((.....))))))))))..)))))).)).)))).))))...(((..((((((((((.(((((((......(((.........)))...))).))))...)))..)))))))...)))......((((((((.((((.(((((..(((.(((......)))))).))))))))).))))))))..))(((((......))))).........((((.......((((.((((.((.((((......(((((....))))).)))).)))))))))).....))))....(((((((.((((.....(((((......((((((((((((((((..((((...((((....))))....))))...))))).)))).))))))).((........)).((((((.....))))))((((((((((((((..(((.....(((((....))))).....))).)))))))).(((((......)))))............))))))(((((...((((..(((((.((.((((((......)))))))).)))))...(((((....)))))........))))))))).....................((((((((((((((......)))..)))).)))))))..............)))))..((((((.((.(((((((...))))))).......))))))))(((((((((((((((..........))))))))(((((((((.....)).)))))))((((..(((((.....((.(((((((((...(((.....)))...))))))))).))..)))))..)))).))))))).)))).)))))))((((((((..................))))))))....(((((((((...........(((((..................))))).................(((((....((((((((((((((................))))......(((((((((...))))))))).(((....))).....)))))))))))))))(((((((((((.((.....((.(((.((((...))))..))).))...)))))))))))))..)))))))))((((...(((.((((((((((..((((((..........))))))....................(((((((.((.((....)).)).)))))))................((((((.(((((((((((((((((..(((((((((((....))))))))...........((((((((........))))))))...........((((...((((((....))))))...))))..)))..))))))))))).)))))).))))))........((((((.(((((((((..((((....)))).)))))..)))))))))).......)))))))))).)))..)))).................(((((((.........((((((.((((((......(((((((((.(((.((((.(((.(((...))).))))))).))).)))).)))))(((.((........)))))..)))))).))))))....(((((((((..(((((((.(((((...(((((.((((...........))))))))).......((((((..((((.(((((((...(((........)))))))))).)).)).))))))....(((((((((((((..............)))))))).)).)))........))))))))))))....))))))))).............(((((((((....)))))))))...........(((((((..(((((((.((.....((((((((....))))))))....)).)))))))..)))))))..............)))))))...(((((...((((......((((((....((((........))))..........(((((.....(((...(((((......)))))...)))...((((((((.....))))))))...)))))............(((((((((...................(((.(((((((.((((.....)))).))))))).))).))))))))).......(((((.......)))))........)))))).....))))....)))))..........(((((((..(((((....((((..((((.....((((((((((((..(((....)))))))))....))))))......)))).))))...((((((((.......))))))))............((.(((.((((((.....((((..((((.((((((.((((((.((((((((.(((....)))..)))))))).))))))...)))))))))).))))....)))))))))))..................((((((((((.......(((((((((..((((((....)))))))))))))))....)))))))).)).........(((((((.........((((((((..((((.....))))...))))))))......))))))).......))))).)))))))(((((...))))).(((((...........)))))......(((((((..((((((.(((.(((((..((((((((........))))))))...))))).............((((.(((.....((((((.(((.....)))))))))...))).))))...(((((((.....((((((((.((((((((...(((.....)))...)))))).)).)))))))).((((((((......)))))))).)))))))...............(((((((...(((.....)))...)))))))..............((((((.....(((.(((((((....))))))).)))))))))..((((((((((.((((((((((((((((......))))).)).....)))...((((((((..((((......((((((((((((.....((((.....)))).))))))))))))......))))..))).)))))..)))))).))))))))))...))))))))).....)))))))..(((((((.((((((......(((((................)))))))))))......((((((....((((....))))....)))))).....(((((((..(((...)))..)))))))..............))))))).....((((((((((.......((((..(((..(((((((((...(((((((......)))))))...)))))))))..........)))..)))).((((....))))(((..((((((((...((((((........))))))(((((.......(((((.((((......))))...)))))((((.........))))...((((((.(((......))).)).)))).....(((((((.......((((....(((((((((......))))..)))))....)))))))))))..(((((((((((((...)))))).....((((.....)))).))))))))))))....(((......)))...((((((((((((.......)))(((.(((((((.((.(((.(((......)))))).))...))))))).))).......)))))))))..((((......))))..))))))))..)))..........)))))))))).........(((((((((...)))))))))....((........((((....))))((((((.((((((.(((......))).))))))((((((.....))))))......((((((((..(((......)))....((((((((((((((......)))))))...)))))))............((((((.....(((((((((((((.(((((..((((((((..(((((((........)))))))......))))))))...))))))))))).................)))))))...))))))....((((((((...))))))))..........((((((((((.(((((.((((....))))..))))))))...))))))))))))))).....((((((...))))))...((((((..........((((((..........))))))...........))))))....)))))))).........((((((.(((......)))))))))....(((((((..(((....((((((((((((((((((.((((((...)))))).((......)).......((((.....))))...))))))))))......))))))))((((((((((...)))))))))).............(((((((....))))))).........(((((((....)).))))).(((((...)))))...((((.((((((.((((((.....)))))).)))))).))))............(((((.....(((((..(((((((((((...))))))))))).))).))((((.....))))))))).....................)))..)))))))..((((((((((...(((..((((((..((.(((......))))).....(((((((((.......................((((((((((....)))))).))))(((.(((((((....(((.((((...(((((((.(((((....((((.(((((......(((((......)))))))))).)))))))))..)))))))....((((((.((((.((((((((......)))))))))))).)))))).)))).))).))))))))))...........((((((((....((((((((....))))))))......))))))))..)))))))))..((((((.....((((....))))......))))))..((((((((((((.((((((((.........))))))))))))))).......))))).((((((......))))))..............(((((((....)))))))..))))))..)))..))))))))))................(((((......)))))((((((.(((((((((....))))))))).)))))).......................(((((((((.....((.((.(((((......)))))))))..)))))))))((((......))))(((((((....)))))))......((((((.((((....((((((.......))))))))))))))))......................................((((......)))).........(((((.(((...(((((.((......((((((..........((((((((..........))))))))...............((((((((.........(((((....)))))...........((((((((.((.(((...)))..........(((..(((((..((((.(((((((..(((.....)))..))))))))))).....)))))..))).((...((((((((((...((........)).)))).))))))))..........((.(((((((.((((......)))).))))))).))))))))))))......((((....((((((((....))))))))))))..(((....))).((((((.((.........)).))))))..............(((((((.....((((.........))))....))))..)))....(((((((((((((.....((((.......))))...)))))))))))))..)))))))).......................))))))....)))))))...))).)))))..((((((.......)))).)).......((((((((((............))))))))))(((((((............((((((((.(((....(((((((((....)))))))))))).......))))))))...(((..((((((((((((((((((..(((.....))).(((((((......)))))))))))))))))...((((.(((.((((....................((((((((.....))))))))......)))).))).))))...(((((((.(((.(((((........)))))..))))))))))))))))))..)))(((((((..........)))))))...................................)))))))............(((..((((((....))))))..))).........(((((((((..((((((.....))))))(((((((..(((((.....)))))))))))).((((((((...........(((((..((((.((((......(((.....)))..))))...))))..))))))))))))).....)))))))))....................(((((.((((((........)))))))))))..............................................................(((((((.(((.((((((....((......)).....)))))).)))..)))))))...............(((((.....)))))............(((((..(((((..............)))))...(((((((....(((.((((((......))).))).)))....))))))).(((((..(((.(((((((.(((((.......))))).))))))).)))......)))))..........)))))............((((....(((((.(((.((((.(((((....))))).))))))))))))....)))).......((((.((((((......))))))))))...................(((((((.(((((......))))))))))))..........................((((((((.......(((........)))....((((((((.(((......)))))))))))........)))))))).............((((((((...((((((..(((((......)))))..))))))((.((((((.(((((((.....)))).))).)))))))).(((((((.....))))))).((((....)))).(((((..(((((.(((((.......((.(((((...((((....((.((((((((((((((((((((....)))))))).)))))))))))).)).....((.(((((((...((((((...((((....))))...)))))).)))))))))...................)))).)))))...))))))).)))))..)))))...............(((((((((((.(((((.(((...((((((((((.....))))).)))))...))).))))).....))))))))))))))))))).....(((((........)))))...........((((((((((.....)))))).))))............................................................(((((((.......)))))))....((((((((((((......((..((((((((((.........))))))))))..)).......((((((..........))))))(((((.......((((((((..((....(((((.......)))))...))..))))))))..(((((...))))).....((((.....((((.((.....(((((.((..(((..((((((((.....((((..(((....)))..)))).....)))))).))..)))..)).)))))......((.(((((((....)))...))))........))............(((((......((((...((((((....))))))..))))........)))))...(((......(((((((.....(((.....)))....))))))).....)))...............))..))))......))))))))).....((..((..(((.((..(((((((((.((....)).)))))))))..)).)))..))..))))))))))))))............(((((((..(((......(((((....)))))....))).)))))))((((((((((.(((.......((((((((..((......)).))))).)))............((..(((((((((.....(((.((((....)))).))).....)))))))))..))(((((((......((((....((.(((((((.....)))).))).))..))))...............((((((...((((...))))..))))))...)))))))((((........))))...(((((((.((((....((......))...(((((.......((((((((((....))).))))))).........................(((...........(((((((((((...((((......))))......)))))))))))..............)))............)))))..((((.(((((((.........))))))).)))).....)))).)))))))......((((((..(((.((((.....(((((.((((....)))).))))).......)))).)))..)))))).....))).))))))))))..((((((((...............))))))))............(((((((((((..................................((((.......((((..........))))(((..(((...((((.((((..((((.((.......)).))))...)))).)))).....)))..))).((..((....((((...((((((.....))))))...))))....))..)).....................)))).............(((((((...(((((((..(((((((((.((.(((....))).)))))))))))....))))))).....)))))))...)))))))))))....................................((((((.....((((((...(((((((((((((.(((.((((.(((....))))))).)))((((((((.............((((..(((...((......)).....)))..))))....(((.....)))..)))))))))))))((((((((..((((((...)))))))))))))).........))))))))....))))))))))))..(((((((((((((((..((.........))..))))).........((((((((((((((((......))))))))..)))))))))))))).))))..(((.(((((((((..........))))))))))))..........(((((((.((((.(((((((.(((((((((..((((((((.....(((..((((((((((......(((((...............((((.(((((((((((.((((((((....))).........((((((.......(((.....(((((((((((.....))))))))))).(((.((((.............((((((.......)))))).................)))).)))...........)))..........)))))).....................)))))..))).)))))))).))))((....))..))))).)))))).))))..)))......)))))))).))))))))).......(((......((((....(((((...((....))...)))))..))))....)))..)))))))..))))...)))))))...................((((((....((..((((.((((.................((.....))................((((....((((.((((((.(((.((((((((......)))))))).))))))))).))))....))))..(((...((((((.....((((((...))))))...))))))....))).((((((.(((.((((.((((((((..(((....)))..))))))))........)))).))).))))))........))))..)))).))..))))))........................((.....(((((........))))).....))......(((....))).............((((.(((((.(((......))).))))).)))).............................................(((((.(((((((((((((((.(((((((((((.....(((((...(((((.....)))))....)))))...)))))))))))))))))))).(((((...................)))))....(((((........)))))....((.(((((((((((........)))))..)))))).)).....(((((..(((((.(((((((......)))).))).))))).))))).......((((((.....((((...((((..((((((..((....(((((.......(((((((.....((((....(((.((((((((..................((((((((((((((....))))))..))))))))...........((((((.....(((.....)))..))))))........)))))))))))......))))...)))).)))....)))))......))..))))))..)))).))))............))))))........))))))...)))))....(((((((..((((((((......))))))))...((((((..................)))))).....(((.......((((((....(((.(((((((..((.(((.((.(((.((((..(((((((((((((...........(((((((.((((((.....((((((((....................((...(((......(((((((...........)))))))......))).....)).......((((....))))...........................))))))))...((....))...........)))).)).)))))))........((((((..(((((....((..(((((((.........))))))))).)))))..))))))))))))).))))))...))))...)))))))).)).)).))))))))..))))))....)))..((((.(((((((.((((....))))......)))))))))))((((....................))))..............)))))))..........((((...(((..................((((.....(((.(((((((.((.......)).)))))))))).....(((((...(((((((((....)))))))))..)))))......(((((((......)))))))........((((..((((............))))..))))......((((((..((((((.(((((((((.....)).))))..))).))))))...))))))(((((((((((..........))).))))))))...............(((((.((((..((....))..))))))))).(((((...........)))))....)))).....((.((.((((...(((....)))..)))).)).))............)))..))))...............................................................((((........))))...................................((((.((..............)).))))((((.(((((.((((...)))).)))))))))((((..(((((((((....)))))))))..)))).....((((((......)))).))((((((((((((...))))))).)))))..........(((((((((((((((..(((((((((.............((((((....(((((.((.((....)).)).)))))....))))))......(((((((....(((((....(((.....))).......))))).......)))))))..))).)))))).(((((....((((....(((((...((((.....)))).))))))))).....))))))))))..))).)))))))......((((..((((((....)))))).))))...........................................(((((...)))))..............((((((...(((.(((((.....)))))..)))...))))))(((((....)))))((((((((((.(((.((((....)))).)))...............))))))))))........................(((((((((((((....)).))).))))))))...............................(((.......)))...................(((((((((((............)))).)))))))..(((((.(((((.....(((((((.((((.......))))))))))).......))))).)))))........(((((((((..(((....((((....)))).))).))))))))).......(((((.((((.(((((.......))))).)))).))))).........(((((((.(((.(((((((.(((((....)))))...))))).))......(((((((......((((((.((((((((((.......)))).)))))).))))))........((..(((((((.(((.........((((..........(((((((((...((....))...)))))))))...((((((((((...(((((((......((((((((.((.....))))))))))....)))))))(((...((((((.(((((((((((((.((((.((((((..((...))..))))))...((((........)))))))).)))))).)))).)))))))))...)))((..((((................))))..))....(((.((((.....)))).)))..))))))))))(((((.....)))))....................((((.((((((.......))))))..))))............))))...)))))))))).))....))))))).(((((.....))))).......))))))))))..(((......)))...(((((.((((((.(((.(((....)))...))).)))).))))))).............(((((.((((.(((......))).)))))))))......(((((((.(((((.(((((.......))))))))..)).))))))).....((((((....))))))...(((((.((((((((.........(((((.(((.(((((((......))))))).....)))...)))))...))))))))))))).................................................................(((((((((..((.......(((((((.(((((...(((.......))))))))))))))).......(((((..((((....))))(((((((((.......))))))))))))))..................(((((((.....)))))))......................(((((..((((((((((................))))))))))))))))).)))))...))))......((((((.....))))))....(((...((((......((((((.((((((((((((.....((((.((.((.((...........)).)).)))))))))..)))))))))..))))))..))))..)))..((((((..(((.(((((...((((((....))))))))))))))...))))))........(((((((((........................((((((((((.(((((((..(((..........))))))...)))).))))))).)))............)))))))))..............(((((.........)))))(((.....)))...................((((.....))))..........(((((...........(((.(((.......)))))).(((((.(((((((((.(((.....)))..)))).)))))..)))))....)))))...............................................((((((.(((((........((....))....(((((..((((((((.(((..........))).)))))))).)))))..))))).))))))......(((((((.((((....)))).)))))))....((((((((........((((((((....)))))))).....((((.....)))).......((((((((....)))))))).......................(((.(((((....((((.........))))....)))))))).))))).)))((((((((((((((((.......)))))))))..................(((((.(((((((((((.......((((.....((((....))))..))))...)))))))).))))))))...)))))))......(((((..(((((((((((((..((...(((.(((.........)))...)))...))(((((((...............)))))))..)))))))..))))))....(((..((((((........))))))..)))...........))))).............(((...((((((((...((((...((((((............(((..(((((((((((((.((((((...)))))).)))))))).)))))...))).............))))))..(((((((((.....((.((.....(((((((.((.(((((((...))))))))).))..))))).....))...))((((((...(((((..(((((((.(((........((..........(((((((......)))))))....))....))))))))))....)))))...))))))......(((....)))...))).)))))).(((.(((((....))))))))............((((...(((((....(((((.((((((((((((.((((((((............)))))))).........))))))))........(((((((((((((((......))))))))).....(((....)))))))))................)))))))))...)))))...))))))))))))))))...)))....((.(((......)))))...........((((((.......))))))(((((((...(((((((.((((.....((((..((((((((((((...............(((((((((.(((..(((((.....((.......(((((((((((...................)))))))).)))....))..(((.((((((.....))))))))).)))))...)))..))))))))).......((((.............)))))))))).))))))...)))))))).))))))))))))))...(((((((((((.((((((.......)))))))).))).....(((((.......((((((((((...(((....))).((((..(((((((.......((((((((((((((((.((((((..(((((((...(((((.....))))).....)).)))))..))))))))))))))).....((((((((...(((.(((((((((((((((((((..((......)).)))))..)))))))))))))).(((((..........)))))..))).....))))))))...(((((((((((....))))))).))))))))))).........................(((((((.......)))))))....)))))))..)))).((((((.......)))))).((((.......)))).................)))))))))).....))))).....((((...))))...)))))).....................(((.......(((...)))......)))(((((((.(((..............)))))))))).((((((((.....))))))))..((((.((((....)))).))))(((((((....(((((..(((((..........((((((((((((((....))))))).))))))).....))))).))))).)))))))...............(((((........(((.((((...)))))))......((.(((.......))).))(((((.......))))).....)))))((((......))))......................((((((..((..((((.(((((.....))))).)))).....))..))).))).........(((((..(((((((((...))))))))).................))))).((((.(((((((.((((.......)))))).))))).))))................((((((((.((((.....))))..))))).)))((((((.(((...((.(((((((((((((((....)))))).)).))).)))))).))).))))))..((((((.........((((((.((((((((.(((((((..((((...((((.....((((((((((((.((((........)))).))))).))....))))).......)))).........))))..)))))))...((((((((((.....))))))))))....................)))))))).............(((((.(((.(((((((.....(((((....)))))...)))))))....)))..)))))...))))))((((((.(((((.(((........)))...)))))((((((..............))))))((((..((......((((...........))))......)).....(((((((.((..(((......))).))))))))).))))...........((((((((........((((....)))).......)))).)))).................((((((...))))))......))))))..))))))......(((.....))).......................(((((((......((((...........((((.......((((((...))))))))))........))))...)))))))............(((((((((((.((...((((((.(((...)))...)))))).....)).)))))).))))).(((((((...(((((...(((((..(((((((((..((.........))..))))))..)))...)))))(((((((((((...)))))))))))..(((((...(((.(((..(((((....)))))))).))))))))....................((((.((((((.....(((((((((((...........((((.....))))...)))))))))))................)))))).)))).)).)))..)))))))..............(.((..(((((((.((((..(((((...)))))..)))))))).)))..))..)...........(((((((......)))))))........((((..((((.........))))..))))..........(((((((((((((((....)))))..))).)))))))...........((((((((((((......))))............(((((.(((.(((..((((((((........))))).)))...)))))))))))..........(((((...(((((.......)))))....))))).................((((((.......)))))).........)))))))).((((((...((((((((.((((.(((.((((((...)))))).))))))).)))))))).))))))((((((((((...(((((((.(((.....)))...)))))))..))))))).)))..................................................................................................................................((........))................(((((((((.((......)).)))))))))((.......((((((.......))))))..))..((((((((((.((.(((.((((...))))))).)).)))))))..)))..............((((((((....))))))))(((((.((((......((((((...((((((((((..............(((((.((........(((((.((((..(((((.....))))).))))..)))))........)).)))))...((((((((((......)))))).)))).((((((...((((((((..((((...((((.((((((.......))))))....))))...)))))))))))).))))))))))).))))).....(((..((((((((......)))))...)))..)))........))))))((((((..........)))))).)))).))))).................((((((....))))))............................(((((.((....(((((((((((((((((((.........(((((.(((((((((......((((((...))))))....))))))))))))))......((((.((((((((.(((((.....))))))))))))))))))))))...)))))))))))))))).)))))...........................(((((.((((...((..((((((((((((((((.((............)).)))))).)))))))).))..))...((((..(((((((((.....))))))))).)))).)))).)))))............(((((........)))))...................(((.....(((((((((..........................................((((((((((.....))))))))))...)))))))))....)))...................((((((.((((..((((((....(((...........)))....))))))..)))).)))))).............(((((..........))))).......((((((((((........................((((((...((((.....))))...))))))))))))))))......(((((((((((((....)))).))))).)))).............................((((...(((.((......)))))...))))...(((((((..((((((((.(((....)))))))))))..)))))))(((((....((.......)).......(((((.((((((....)))))))))))............))))).....((((((.(((..((((((((((((((((((((((((((((..(((..(((((...))))))))))))))))).)).)))))))).)))))...)).))..))).))))))........((((((.(((.....))).)))))).....((.(((((.......((((((((((..............))))).)))))))))).))............((((..........))))..................((((.....((((((((((.....((((((.....))))))...))))..)))))).....))))((((.((((((......)))))).))))..((((((((.(((((..........((((((.((((((...))))))....((((((..((.......(((((..((((((((...))))))))...))))).....)))))))))))))).................................................................((((.....))))((((........)))).((((.((((........)))).))))........))))).................(((((((((.((.......))...)))))))))...))))))))..................(((((((....))))))).............................(((((((((((((((.(((((((..(((...)))..))))))).))))..))).))))))))((((((((..........))))))))............................(((.((((((((((.....)))).))))))...........)))..........(((.((((..(((((.(((((((....)))))))...)))))...)))).)))............((((((........))))))......((((((((((((((....((((((.(((((((..................)))))))))))))(((((((......))).))))....))))).)))))))))..........(((((((((......)))))).)))......(((((((((..(((((....((((.((......))))))..)))))..))))))))).................(((((......))))).......((((((......))))))......................................((((((((......((((((((((..................)))))))((((((((..(((((((.....((((((.............((((((..((((.((.........)).))))..))))))........................))))))))))))).))))))))....)))....))))))))...(((..((((.((((((((((((((((((...)))))))))).)))).))))......))))))).............................(((.(((.((((..(((((((..(((((...((....))....))))).)))))))...))))))).)))..((((((.((.(((..(((((......)))))..)))))))))))..(((((((.(((((((...((.(((.(((((((.....)))))))))).))...((((((((....)))))))).))))))))))))))..((((((.((((((..(((((((((..(((((.......))))).)))).......((((......))))(((......(((((.......)))))....))).............)))))..))))))...((((..(((((((......)).)))))..))))...))))))....................................((((((((...((((((.......)))))).............((((..((((((......((((.....)))).....))))))..))))....((((((((........(((((((((.............)))))))))..((((((((((.(((((..((((.(((...))).))))...........((((((..(((((........)))))))))))((((....))))..((((((...((((......))))...))))))..))))))))))))...)))....((((((((((((.......))))...............((((((((((((.....(((........))).....)))))))).))))........))))))))....((((((.((.(((....)))))))))))......(((((((......)))))))......))))))))............((.((((.(((((((((((...................)))))))))))..)))).)).........))))))))..............((.(((((((((...................(((((((((((...(((((..((((((.......))))))..))))).(((((...)))))))))))))))).......(((((((((....(((((.((((..((((((((...((((...........))))...))))......((((((((((.....((((((.........))))))((((((((..................((((((((.........))))))))..........((..(((((((((((...............(((((..((((((..(((((((.....)))))))...)))))).))))).......(((.((((((.......))))))..))))))))))))))..))...........))))))))......))))))))))...........))))...))))..))))).......................(((((((......((((.((((((....)))))).))))..))))))).))))))))).......((((((((...))))))))......)))...)))))).))((((((((......((((((...))))))......(((((((((((.................)))))))...))))....(((((.((.....)).)))))..((((((....)))))).(((((((((((....(((((......((((.(((((((............((.(((....))).)).....)))))))))))...........((((.((((((((...)))))))))))))))))........))))))))))).(((((((....))))))).......)))))))).................(((((..........)))))..................((((((((((.(((((((((..............(((((((.....(((.(((((...........))))))))...)))))))(((....))).....(((((((((...(((....)))..))))..)))..))........((((.(((((((((((((..........((((.((((((((.....))))))))))))....))))))))..................(((((((.......(((........)))......((((((.........))))))..(((((((.(((((.............))))).))))))).....)))))))......................))))).))))................(((((.(((((....))))))))))))))).))))))))))))))...............................(((...(((((...)))))...)))..............(((((((.....(((((....)))))....))))).)).........((((((.........))))))((((.((((((.(((.((((((((((....))))...)))))).)))..)))))).))))..((((.((((..(((((((((((....))))))).)))).)))).)))).............((((((((((....))))...)))))).............((((((((((........)))))))))).............(((((((.(((.......((((((((.(((..(((((......)))))..(((((((...(((((..(((((((...((((((.(((((....(((.....))).)))))..))))))))))))).......(((.....))))))))...)))))))..............(((..((((((.((((......((((((((.....(((((.(((....((....))....)))))))).......)))))))))))).))))))...(((......)))......))).........((((((......((((((((((((....))))))))))))......))))))))).)))))))).....))).))))))).....((((.......)))).............((((.(((((((.....(((((.(((((((((.....)))))))))))))).........((((((((((...)))))))))).......(((((((((.....(((((((((.....)))))))))...))))..))))).((((((((((..((((((((......))))))))..)).)))))))).....(((((((((((((((.....))))))))))...)))))..((.(((((((..((((((((((.((((.....)))).))))))...))))))))))).))....((((((((((((((((((((..((((((....((((....))))..))))))..))))))))).....(((((.((((((((((.....(((....)))(((((((((........))))))))).(((((....))))))))))))))).)))))...((((.............))))..(((((((.....((((((...))))))......)))))))..))))))))))).))).))))))))........(((.((((..(((((((......)))))))...)))).))).......(((.(((((((...)))))))..)))..(((((((....................(((((((((((((..((((..(((((((................((((((((....))))))))..(((((.....)))))..........((((((((....)))))))).....((......))..........(((((...((((((.((....)).))))))..))))).......)))))))..)))).((((((.....)))))).(((..((((..((.....))..))))..))).)))))....(((((((.(((((((((((.((((((((((..((..((((...((((.(((.(((((...))))).)))..)))).....)))).))))))).))).))))))))).)))).)))))))...)))))))).............((((((.....))))))......)))))))..(((((((((..(((..((.((((((((((..(((.(((.....))))))))))).))))).)).)))..))))))).))..........((((((((.....((...(((((..((((((((..((((.((((((............))))))))))....)))))))))))))))))))))))..........((.(((((.(((.(((.....................))).))).)))))....))..........((((......((((.((.(((((((((...))))).)))).....))..))))...)))).(((((.........(((((((((.......(((.((((....)))).)))..............)))))))))........)))))......((((.((((((......)))))).))))....((((((......((((..............................(((((((...((((((..(((((.....)))))..))))))...))))))).....(((((((((....)))))))))...((...((((((((...........)))))))).)).........((((((..(((((.........((((.(((..((...((((.......))))...))..)))((((.(((((.....)))))..))))....))))..((.((((((.....)))))).)))))))...))))))(((((((................(((((((....((((.(((((.((((((...))))))))))).)).)).....)))))))........))))))).(((.....)))))))......)))))).........((((((......(((((.((((((......(((((.((((((......)))))).))))))))))))))))........(((((..(((((.((....)).)))))..)))))............(((((((((((((......)))))))))).)))(((((((((((..(((((((........)))))))(((((..((((.....((((((((((((........))))))))))))((........))........(((((..(((((.((((((.((.((((.....))))))))))))))))))))))...(((((((..((((....))))...............)))))))))))........)))))((((((((((.(((.....))).)))).)))))).....))))).))))))(((((......(((((((...))))))))))))..........((((((....((.((((((.....(((.(((((.....))))).))))))).)).)).)))))).....))))))......((((.(((.((((((((((((.((((.........)))))))))).((....))........))))))))).))))...(((((((.......((((((((((..(((.....(((.....)))..)))..))))..(((.(((((.(((.(((((((.........((((((..(((((....(((((((..........)))))))..))))).............((((((.((.(((((....))))).)).))).)))))))))...)))))))...)))))))).)))......((((((.....(((((((......(((.(((........................))).))))))))))........))))))...............((((....)))).....))))))....((..(((((..((.(((((((((((.(((......))).))))).))))))..)).)))))..))..............(((((((.(((((((((((((((((...))))))))).....(((.(((((.((((((...)))))).)))))..)))))))))))..)).)))))......))))))).....(((((.....((((...........)))).....(((..............((((((((((((...))))))))))))...((((.(((((...(((((................))))).)))))))))(((((.........(((((.....))))))))))........(((((........))))).........(((..(((((((....)))))))..)))((((....((((((....)))))).))))...)))...((((......))))(((((.(((((..((((....)))))))))....((((((.......))))))..............((((...((((.....))))...))))............)))))..........((......))...........((((((((......)).))))))...((((.((.((((((.((((....))))...))))))))))))(((((.((((((.......))))))...)))))......((((((.((..((((......))))..))...)))))))))))..((((((..((.(((((((((((..(((...((......))...))).)))))))))))))))))))........((((((.(((((((((.((....))..)))))))))...((((..((((((((((..((..(((.(((.....(((((((((.((.(((....))))).((.(((((((((....((.((.((.........)).))))...))))).))))...)).....((.((.....)).))..))))))))).....))).)))..))...))))......))))))..))))...........))))))....................................";
	// String seq = "AUUAAAGGUUUAUACCUUCCCAGGUAACAAACCAACCAACUUUCGAUCUCUUGUAGAUC";
	// String str = "......(((((.(((((....)))))..)))))...........(((((.....)))))";

	GenomePanel _selected;

	GenomePanel _gpModel;

	JComboBox<String> _probing;
	DefaultListModel<String> _probingModels;
	JFileChooser _fileChooser;
	JCheckBox _modelCB;
	JCheckBox _syncZoom;
	JPanel _gpPanel;
	SpinnerNumberModel _bpSpan;
	JPanel _applyToOption;
	JList<PANEL_APPLICATION_OPTIONS> _applyToOptionList;

	Hashtable<String, double[]> _vals = new Hashtable<String, double[]>();

	public GenomeGUI() {
		super("SARS CoV 2 Structure Viewer v0.1");

		_gpRef = new GenomePanel(this,_seqRef, _strRef);
		char[] chars = new char[_seqRef.length()];
		Arrays.fill(chars, '.');
		_gpModel = new GenomePanel(this,_seqRef, new String(chars));
		_gpRef.setPreferredSize(new Dimension(-20 + (int) Toolkit.getDefaultToolkit().getScreenSize().getWidth(), 600));
		init();
	}

	private JLabel styleToolBarHeader(String msg) {
		JLabel lbl = new JLabel(msg);
		Font f = lbl.getFont();
		f = f.deriveFont(18.f);
		f = f.deriveFont(Font.BOLD);
		lbl.setForeground(FOCUS_COLOR);
		lbl.setFont(f);

		return lbl;
	}

	private class TitledGenomePanelBorder implements Border {
		LineBorder _outline;
		TitledBorder _title;

		public TitledGenomePanelBorder(String msg, int thickness, Color c, float fontSize) {
			_outline = (LineBorder) BorderFactory.createLineBorder(c, thickness);
			_title = BorderFactory.createTitledBorder(_outline, msg);
			Font f = _title.getTitleFont();
			f = f.deriveFont(fontSize);
			_title.setTitleColor(c);
			_title.setTitleFont(f);
		}

		public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
			_title.paintBorder(c, g, x, y, width, height);
		}

		@Override
		public Insets getBorderInsets(Component c) {
			return _title.getBorderInsets(c);
		}

		public boolean isBorderOpaque() {
			return _title.isBorderOpaque();
		}

		public void setColor(Color c) {
			_outline = (LineBorder) BorderFactory.createLineBorder(c, _outline.getThickness());
			_title.setTitleColor(c);
			_title.setBorder(_outline);
		}

		public void setTitle(String msg) {
			_title.setTitle(msg);
			;
		}
	}

	public static final String CSV_EXT = ".csv";
	public static final String DATA_EXT = ".dat";
	public static final String TEXT_EXT = ".txt";
	public static final String DBN_EXT = ".dbn";
	public static final String CT_EXT = ".ct";
	public static final String CHAIN_EXT = ".chain";
	public static final String FASTA_EXT = ".faa";
	public static final String FASTA2_EXT = ".fasta";
	public static final String STRUCT_EXT = ".str";
	public static final String SVG_EXT = ".svg";
	public static final String BED_EXT = ".bed";
	public static final String RNA2D_EXT = ".rna2d";

	private class CustomFileFilter extends FileFilter {
		String[] _ext;
		String _desc;

		public CustomFileFilter(String[] ext, String desc) {
			_ext = ext;
			_desc = desc;
		}

		public boolean accept(File f) {
			if (f.isDirectory()) {
				return true;
			}
			String fname = f.getName().toLowerCase();
			for (int i = 0; i < _ext.length; i++) {
				if (fname.endsWith(_ext[i]))
					return true;
			}
			return false;
		}

		public String getDescription() {
			String txt = "";
			for (int i = 0; i < _ext.length; i++) {
				if (i > 0) {
					txt += ";";
				}
				txt += "*" + _ext[i];

			}
			return _desc + " (" + txt + ")";
		}

	}

	private FileFilter _valuesFF = new CustomFileFilter(new String[] { CSV_EXT, TEXT_EXT, DATA_EXT },
			"SHAPE reactivities as Comma-separated file");
	private FileFilter _inputFF = new CustomFileFilter(
			new String[] { FASTA_EXT, FASTA2_EXT, DBN_EXT, CHAIN_EXT, CT_EXT }, "RNA sequence/structure file");
	private FileFilter _structureFF = new CustomFileFilter(new String[] { STRUCT_EXT }, "Detailed structure file");
	private FileFilter _sequenceFF = new CustomFileFilter(new String[] { FASTA_EXT }, "Sequence file");
	private FileFilter _exportFF = new CustomFileFilter(new String[] { SVG_EXT },
			"Scalable Vector Graphics (SVG) file");
	private FileFilter _annotationsFF = new CustomFileFilter(new String[] { BED_EXT },
			"Browser Extensible Data (BED annotations) file");
	private FileFilter _rna2DFF = new CustomFileFilter(new String[] { RNA2D_EXT },
			"RNA 2D Layout file");

	private enum PANEL_APPLICATION_OPTIONS {
		APPLY_SELECTED_MODEL("Selected"), APPLY_REFERENCE_MODEL("Reference"), APPLY_NEW_MODEL("New model"), APPLY_BOTH(
				"Both");

		String msg;

		PANEL_APPLICATION_OPTIONS(String s) {
			msg = s;
		}

		public String toString() {
			return msg;
		}
	};

	private ArrayList<GenomePanel> getPanels(PANEL_APPLICATION_OPTIONS tt) {
		ArrayList<GenomePanel> result = new ArrayList<GenomePanel>();
		switch (tt) {
		case APPLY_SELECTED_MODEL:
			if (_selected != null) {
				result.add(_selected);
			}
			break;
		case APPLY_REFERENCE_MODEL:
			result.add(_gpRef);
			break;
		case APPLY_NEW_MODEL:
			result.add(_gpModel);
			break;
		case APPLY_BOTH:
			result.add(_gpRef);
			result.add(_gpModel);
			break;
		}
		return result;
	}

	private void populatePanels() {
		if (_modelCB.isSelected() && (_gpPanel.getComponentCount() != 2)) {
			_gpPanel.setLayout(new GridLayout(0, 2));
			_gpPanel.add(_gpRef);
			_gpPanel.add(_gpModel);
			_gpPanel.repaint();
		} else if ((!_modelCB.isSelected()) && (_gpPanel.getComponentCount() != 1)) {
			_gpPanel.setLayout(new GridLayout(0, 1));
			_gpPanel.add(_gpRef);
			_gpPanel.repaint();
		}
	}

	private void updateBorders() {
		updateBorder(_gpRef);
		updateBorder(_gpModel);
	}

	private void updateBorder(Object o) {
		if (o instanceof GenomePanel) {
			GenomePanel gp = (GenomePanel) o;
			Border b = gp.getBorder();
			if (b instanceof TitledGenomePanelBorder) {
				TitledGenomePanelBorder tb = (TitledGenomePanelBorder) b;
				String msg = "Structure: " + gp.getStructureDescription() + " - SHAPE: " + gp.getProfileDescription();
				if (gp == _selected) {
					tb.setColor(FOCUS_COLOR);
					msg += " [selected]";
				} else {
					tb.setColor(NO_FOCUS_COLOR);
				}
				tb.setTitle(msg);
				gp.setBorder(tb);
			}
			gp.repaint();
		}

	}

	public static final Color FOCUS_COLOR = Color.black;
	public static final Color NO_FOCUS_COLOR = Color.gray;

	private void init() {
		setLayout(new BorderLayout());
		_gpPanel = new JPanel();		
		add(_gpPanel,BorderLayout.CENTER);
		
		
		
		float fontSize = 24.f;
		_gpRef.addGenomePanelChangeListener(this);
		TitledGenomePanelBorder title = new  TitledGenomePanelBorder("Reference model",4,this.FOCUS_COLOR,fontSize); 
		_gpRef.setBorder(title);
		_gpRef.addFocusListener(new FocusListener() {
			public void focusGained(FocusEvent e) {
				updateBorder(e.getSource());
			}
			public void focusLost(FocusEvent e) {
				updateBorder(e.getSource());
			}			
		});
		_gpRef.addFocusListener(this);
		_gpRef.setProfileDescription("N/A");
		_gpRef.setStructureDescription("SHAPE-In-Vitro-Manfredonia-NAR-2020");
		_selected = _gpRef; 
		
		_gpModel.addGenomePanelChangeListener(this);
		
		title = new TitledGenomePanelBorder("New model",4,this.NO_FOCUS_COLOR,fontSize); 
		_gpModel.setBorder(title);
		_gpModel.addFocusListener(new FocusListener() {
			public void focusGained(FocusEvent e) {
				updateBorder(e.getSource());
			}
			public void focusLost(FocusEvent e) {
				updateBorder(e.getSource());
			}			
		});
		_gpModel.addFocusListener(this);
		_gpModel.setProfileDescription("N/A");
		_gpModel.setStructureDescription("Empty (load below...)");


		_fileChooser = new JFileChooser();
		_fileChooser.setMultiSelectionEnabled(true);
		_fileChooser.setCurrentDirectory(new File("."));



		JToolBar toolbar = new JToolBar();
		toolbar.setLayout(new FlowLayout(FlowLayout.LEFT));
		_probingModels = new DefaultListModel<>();
		_probing = new JComboBox<String>();
		_probing.setEditable(false);
		_probing.addItemListener(new ItemListener() {
			public void itemStateChanged(ItemEvent e) {
				String index = (String)_probing.getSelectedItem();
				setSHAPE(index);
			}});
		
		_applyToOption = new JPanel();
		_applyToOption.setLayout(new BorderLayout());
		_applyToOption.add(new JLabel("Apply to:"),BorderLayout.NORTH);
		_applyToOptionList = new JList<PANEL_APPLICATION_OPTIONS>(PANEL_APPLICATION_OPTIONS.values()); 
		_applyToOption.add(_applyToOptionList,BorderLayout.CENTER);
		
		
		JButton openStructButton = new JButton("Load model...");
		openStructButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				_fileChooser.setMultiSelectionEnabled(false);
				_fileChooser.resetChoosableFileFilters();
				_fileChooser.addChoosableFileFilter(_structureFF);
				_fileChooser.addChoosableFileFilter(_sequenceFF);
				_fileChooser.addChoosableFileFilter(_rna2DFF);

				_applyToOptionList.setSelectedValue(PANEL_APPLICATION_OPTIONS.APPLY_SELECTED_MODEL, true);
				_fileChooser.setAccessory(_applyToOption);
				int result = _fileChooser.showOpenDialog(GenomeGUI.this);
				if (result == JFileChooser.APPROVE_OPTION) {
					try {
						File selectedFile = _fileChooser.getSelectedFile();
						String fn = selectedFile.getName().toLowerCase();
						int j = fn.lastIndexOf('.');
						if (j != -1) {
							String ext = fn.substring(j);
							switch (ext) {
							case CHAIN_EXT: {
								GenomeModel g = GenomeModel.loadDBN(selectedFile);
								setModel(g, _applyToOptionList.getSelectedValue());
								break;
							}
							case CT_EXT: {
								GenomeModel g = GenomeModel.loadCT(selectedFile);
								setModel(g, _applyToOptionList.getSelectedValue());
								break;
							}
							case FASTA_EXT:
								setSequence(selectedFile, _applyToOptionList.getSelectedValue());
								break;
							case RNA2D_EXT:
								GenomeModel g = GenomeModel.loadRNA2D(selectedFile);
								setModel(g, _applyToOptionList.getSelectedValue());								
								break;
							case DBN_EXT:
							case FASTA2_EXT:
							case STRUCT_EXT:
								JOptionPane.showMessageDialog(GenomeGUI.this, "Error: Unimplemented load option",
										"Dialog", JOptionPane.ERROR_MESSAGE);
								break;
							}
						}
					} catch (NumberFormatException | IOException e1) {
						// TODO Auto-generated catch block
						e1.printStackTrace();
					}

				}
			}
		});
		
		JButton saveStructButton = new JButton("Save model/layout...");
		saveStructButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				_fileChooser.setMultiSelectionEnabled(false);
				_fileChooser.resetChoosableFileFilters();
				_fileChooser.addChoosableFileFilter(_structureFF);
				_fileChooser.addChoosableFileFilter(_sequenceFF);
			}
			});
		openStructButton.setFocusable(false);


		JButton openSHAPEButton = new JButton("Add profile(s)...");
		openSHAPEButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				_fileChooser.setMultiSelectionEnabled(true);
				_fileChooser.resetChoosableFileFilters();
				_fileChooser.addChoosableFileFilter(_valuesFF);
				_fileChooser.setFileFilter(_valuesFF);
				
				_applyToOptionList.setSelectedValue(PANEL_APPLICATION_OPTIONS.APPLY_SELECTED_MODEL, true);
				_fileChooser.setAccessory(null);
				int result = _fileChooser.showOpenDialog(GenomeGUI.this);
				if (result == JFileChooser.APPROVE_OPTION) {
					File[] selectedFiles = _fileChooser.getSelectedFiles();
					for(int i=0;i<selectedFiles.length;i++) {
						File selectedFile = selectedFiles[i];
						String fn = selectedFile.getName().toLowerCase();
						int j = fn.lastIndexOf('.');
						if (j!=-1)
						{
							String ext = fn.substring(j);
							switch(ext) {
							case CSV_EXT:
							case DATA_EXT:
							case TEXT_EXT:
								String profname = fn.substring(0,j);
								if (!_vals.containsKey(profname)) {
									parseSHAPEValues(selectedFile);
									saveSHAPEValues(profname);		   
								} 	
								break;
							}
						}
					}
				}
			}
		});
		openSHAPEButton.setFocusable(false);

		JButton openBEDButton = new JButton("Open...");
		openBEDButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				_fileChooser.setMultiSelectionEnabled(false);
				_fileChooser.resetChoosableFileFilters();
				_fileChooser.addChoosableFileFilter(_annotationsFF);
				_fileChooser.setFileFilter(_annotationsFF);

				
				_applyToOptionList.setSelectedValue(PANEL_APPLICATION_OPTIONS.APPLY_SELECTED_MODEL, true);
				_fileChooser.setAccessory(null);
				int result = _fileChooser.showOpenDialog(GenomeGUI.this);
				if (result == JFileChooser.APPROVE_OPTION) {
					File selectedFile = _fileChooser.getSelectedFile();
					String fn = selectedFile.getName().toLowerCase();
					int j = fn.lastIndexOf('.');
					if (j != -1) {
						String ext = fn.substring(j);
						switch (ext) {
						case BED_EXT:
							ArrayList<Annotation> ann = Annotation.loadBED(selectedFile);
							_gpRef.setAnnotations(ann);
							_gpModel.setAnnotations(ann);
							break;
						}
					}
				}
			}
		});
		openBEDButton.setFocusable(false);

		
		JButton exportButton = new JButton("Export to SVG");
		exportButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				_fileChooser.setMultiSelectionEnabled(false);
				_fileChooser.resetChoosableFileFilters();
				_fileChooser.addChoosableFileFilter(_exportFF);
				_fileChooser.setAccessory(null);

				int result = _fileChooser.showSaveDialog(GenomeGUI.this);

				if (result == JFileChooser.APPROVE_OPTION) {
					File f = _fileChooser.getSelectedFile();
					if (f.exists()) {
						int response = JOptionPane.showConfirmDialog(null, //
								"Do you want to replace the existing file?", //
								"Confirm", JOptionPane.YES_NO_OPTION, //
								JOptionPane.QUESTION_MESSAGE);
						if (response == JOptionPane.YES_OPTION) {
							_gpRef.exportSVG(f);
						} 
					}
					else {
						_gpRef.exportSVG(f);
					}
				}}
			});
		exportButton.setFocusable(false);


		JButton cycleButton = new JButton("Cycle");
		cycleButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if (_probing.getItemCount()>0) {
				int nsel = (_probing.getSelectedIndex()+1) % _probing.getItemCount();
				_probing.setSelectedIndex(nsel);
				}
			}});
		cycleButton.setFocusable(false);
		
		_modelCB = new JCheckBox(" Show second panel");
		_modelCB.setSelected(false);
		_modelCB.addChangeListener(new ChangeListener() {
			public void stateChanged(ChangeEvent e) {
				if(_modelCB.isSelected()) {

					if (_gpPanel.getComponentCount()<2) {
						_gpPanel.add(_gpModel);
						_gpPanel.doLayout();
					}
				}
				else {
					if (_gpPanel.getComponentCount()==2) {
						_gpPanel.remove(_gpModel);
						_gpPanel.doLayout();
					}
				}
			}
		});
		_modelCB.setFocusable(false);
		
		_syncZoom = new JCheckBox(" Sync Zoom level");
		_syncZoom.setSelected(false);
		_syncZoom.setFocusable(false);
		
		_bpSpan =
				new SpinnerNumberModel(this.DEFAULT_MAX_BP_SPAN,
						1,
						5000,
						10);
		JSpinner bpSpanSpinner = new JSpinner(_bpSpan);
		bpSpanSpinner.addChangeListener(new ChangeListener() {
			public void stateChanged(ChangeEvent e) {
				_gpRef.setMaxBPSpan(_bpSpan.getNumber().intValue());
				_gpModel.setMaxBPSpan(_bpSpan.getNumber().intValue());
			}			
		});
		bpSpanSpinner.setFocusable(false);
		
		JButton SHAPECMButton = new JButton("SHAPE Color Map");
		SHAPECMButton.addActionListener(new ActionListener() {

			public void actionPerformed(ActionEvent e) {
				_gpRef.setSHAPEColorMap();
				_gpModel.setSHAPEColorMap();
				_gpRef.repaint();
				_gpModel.repaint();
			}
			
		});
		JButton ProbButton = new JButton("Bolz Prob Color Map");
		ProbButton.addActionListener(new ActionListener() {

			public void actionPerformed(ActionEvent e) {
				_gpRef.setBoltzmannProbsColorMap();
				_gpModel.setBoltzmannProbsColorMap();
				_gpRef.repaint();
				_gpModel.repaint();
			}
			
		});

		toolbar.add(styleToolBarHeader("File"));  
		toolbar.addSeparator(new Dimension(10,10));
		toolbar.add(openStructButton);

		JToolBar toolbarAnnot = new  JToolBar();
		toolbarAnnot.setLayout(new FlowLayout(FlowLayout.LEFT));
		toolbarAnnot.add(styleToolBarHeader("Annotations"));  
		toolbarAnnot.addSeparator(new Dimension(20,10));
		toolbarAnnot.add(styleToolBarHeader("Reactivities"));  
		toolbarAnnot.addSeparator(new Dimension(10,10));
		toolbarAnnot.add(openSHAPEButton);
		toolbarAnnot.add(new JLabel(" Selected: "));  
		toolbarAnnot.add(_probing);
		toolbarAnnot.add(cycleButton);
		toolbarAnnot.addSeparator(new Dimension(20,10));
		toolbarAnnot.add(styleToolBarHeader("Regions"));
		toolbarAnnot.addSeparator(new Dimension(10,10));
		toolbarAnnot.add(openBEDButton);

		
		JToolBar toolbarMisc = new  JToolBar();
		toolbarMisc.setLayout(new FlowLayout(FlowLayout.LEFT));
		//toolbar.addSeparator(new Dimension(30,10));
		toolbarMisc.add(styleToolBarHeader("View"));  
		toolbarMisc.addSeparator(new Dimension(10,10));
		toolbarMisc.add(_modelCB);
		toolbarMisc.add(_syncZoom);
		toolbarMisc.add(new JLabel(" Max BP span: "));
		toolbarMisc.add(bpSpanSpinner);
		toolbarMisc.addSeparator(new Dimension(20,10));
		toolbarMisc.add(new JLabel("Color map: "));  
		toolbarMisc.add(SHAPECMButton);
		toolbarMisc.add(ProbButton);

		populatePanels();
		updateBorders();
		
		_gpRef.requestFocus();
		
		JPanel toolbars= new JPanel();
		toolbars.setLayout(new BoxLayout(toolbars, BoxLayout.Y_AXIS));
		
		toolbars.add(toolbar);
		toolbars.add(toolbarAnnot);
		toolbars.add(toolbarMisc);
		this.add(toolbars,BorderLayout.PAGE_START);
		}
		private static String COMMA_DELIMITER = ",";
		

		public void parseSHAPEValues(File path){

			try { 
				BufferedReader br = new BufferedReader(new FileReader(path));
				String line;
				String fn = path.getName();
				int j = fn.lastIndexOf('.');
				if (j!=-1)
				{ fn = fn.substring(0,j); }

				while ((line = br.readLine()) != null) {
					String[] data = line.split(COMMA_DELIMITER);
					if (data.length>1)
					{	
						try {
							int index = Integer.parseInt(data[0])-1;
							double val = Double.parseDouble(data[1]);
								_gpRef.getRNA().setValue(index, val);
						} catch (NumberFormatException e) {
							// Nan
						}
					}
				}
				br.close();
				_gpModel.getRNA().setValues(_gpRef.getRNA().getValues());
			} catch (FileNotFoundException e) {
				e.printStackTrace();
			} catch (IOException e) {
				e.printStackTrace();
			}
		}

		private void saveSHAPEValues(String name) {
			_vals.put(name, _gpRef.getRNA().getValues());
			_probing.addItem(name);
		}

		private void setSHAPE(String s) {
			if (!_gpRef.getProfileDescription().equals(s))
			{
				_gpRef.getRNA().setValues(_vals.get(s));
				_gpRef.setUseColorMap(true);
				_gpRef.setProfileDescription(s);
				_gpRef.repaint();
			}
			if (!_gpModel.getProfileDescription().equals(s))
			{
				_gpModel.getRNA().setValues(_vals.get(s));
				_gpModel.setUseColorMap(true);
				_gpModel.repaint();
				_gpModel.setProfileDescription(s);
			}
			updateBorders();
		}
		

		private void setModel(GenomeModel g, PANEL_APPLICATION_OPTIONS tt) {
				try {
					for(GenomePanel gp : getPanels(tt)) {
						
						gp.setRNA(g);
						gp.setStructureDescription(g.getDescription());
						gp.repaint();
					}
					updateBorders();
				} catch (NumberFormatException e) {
				}


		}

		private void setSequence(File path, PANEL_APPLICATION_OPTIONS tt) {
			try { 
				String fn = path.getName();
				int j = fn.lastIndexOf('.');
				if (j!=-1)
				{ fn = fn.substring(0,j); }
				BufferedReader br = new BufferedReader(new FileReader(path));
				String line;

				while ((line = br.readLine()) != null) {
					String s = line.trim();
					if (s.length()>1) {
						char c = s.charAt(0);
						if ((c!='>') && (c!='.') && (c!='(') && (c!='[')) {
							try {
								for(GenomePanel gp : getPanels(tt)) {
									gp.setSequence(s);
									gp.repaint();
								}
								updateBorders();
							} catch (NumberFormatException e) {
							}
							
						}
					}
				}
				br.close();
			} catch (FileNotFoundException e) {
				e.printStackTrace();
			} catch (IOException e) {
				e.printStackTrace();
			}

		}
		
		


		public static void setUIFont (javax.swing.plaf.FontUIResource f){
		    java.util.Enumeration keys = UIManager.getDefaults().keys();
		    while (keys.hasMoreElements()) {
		      Object key = keys.nextElement();
		      Object value = UIManager.get (key);
		      if (value instanceof javax.swing.plaf.FontUIResource)
		        UIManager.put (key, f);
		      }
		    } 
		
		
		public static void main(String[] args) {
			setUIFont (new javax.swing.plaf.FontUIResource("Tahoma",Font.PLAIN,18));
			GenomeGUI d = new GenomeGUI();
			d.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
			d.pack();
			d.setExtendedState(JFrame.MAXIMIZED_HORIZ); 
			d.setVisible(true);
		}

		@Override
		public void onGenomePanelChanged(GenomePanelChange tt, GenomePanel source) {
			GenomePanel other = _gpModel;
			if (source==other) {
				other = this._gpRef;
			}
			switch(tt) {
				case SHIFT_CHANGED:
					Couple<Integer,Integer> interval =  source.getVisibleInterval();
					//other.showPart(interval.first,interval.second);
					break;
				case ZOOM_CHANGED:
					if (this._syncZoom.isSelected())
					{ other.setZoomLevel(source.getZoomLevel()); }
					break;					
			}
			repaint();
		}

		@Override
		public void focusGained(FocusEvent e) {
			Object src  = e.getSource();
			if (src instanceof GenomePanel) {
				_selected = (GenomePanel) src;
			}
			updateBorders();
		}

		@Override
		public void focusLost(FocusEvent e) {
			// TODO Auto-generated method stub
			
		}
		
		
	}
